%%%%% Set up %%%%%

% Set document style and font size
\PassOptionsToPackage{table}{xcolor}
\documentclass[12pt]{article}

% File path to resources (style file etc)
\newcommand{\locRes}{../../TechnicalReport/Document}

% Style file for DFO Technical Reports
\usepackage{\locRes/TechReport}
% \usepackage{draftwatermark}  % Draft watermark

%%%%% Variables %%%%%

% Species names
\newcommand{\fishName}{Pacific Herring}
\newcommand{\scienceName}{\emph{Clupea pallasii}}

% Title
\newcommand{\trTitle}{Calculate the spawn index for \fishName{} (\scienceName{}) in British Columbia, Canada}

% Publication year
\newcommand{\trYear}{2021}

% Publication number
\newcommand{\trReportNum}{nnnn}

% ISBN
\newcommand{\trISBN}{xxx-x-xxx-xxxxx-x}

% Author names: this is all cludgy but it works (including the affiliations)
\newcommand{\trAuthsLong}{Matthew H.~Grinnell$^1$, Jake F.~Schweigert$^2$, Matt Thompson$^1$, Sarah Hawkshaw$^3$, and Jaclyn S.~Cleary$^1$}

% Author names without
\newcommand{\trAuthsNoMath}{Matthew H.~Grinnell, Jake F.~Schweigert, Matt Thompson, Sarah Hawkshaw, and Jaclyn S.~Cleary}

% Author names reversed (for citation)
\newcommand{\trAuthsBack}{Grinnell, M.H., Schweigert, J.F., Thompson, M., Hawkshaw, S., and Cleary, J.S.}

% Address
\newcommand{\trAddy}{Fisheries and Oceans Canada\\
Science Branch, Pacific Region\\
Pacific Biological Station\\
3190 Hammond Bay Road\\
Nanaimo, BC \enskip V9T 6N7}

% Affiliations
\newcommand{\trAffil}{
$^1$ Pacific Biological Station, Fisheries and Oceans Canada,\\
3190~Hammond Bay Road, Nanaimo, British Columbia, V9T 6N7\\
$^2$ Emeritus, Pacific Biological Station, Fisheries and Oceans Canada,\\
3190~Hammond Bay Road, Nanaimo, British Columbia, V9T 6N7\\
$^3$ Institute of Ocean Sciences, Fisheries and Oceans Canada,\\
9860~W.~Saanich Road, Sidney, British Columbia, V8L 5T5
}

% Abstract
\newcommand{\trAbstract}{
The spawn index time series is one component of \fishName{} (\scienceName{}) stock assessments in British Columbia, Canada.
This document describes how we calculate the spawn index from spawn survey observations (e.g., spatial extent, number of egg layers, substrate type).
There are three types of spawn survey observations:
(1) observations of spawn taken from the surface usually at low tide;
(2) underwater observations of spawn on giant kelp, Macrocystis (\emph{Macrocystis} spp.); and
(3) underwater observations of spawn on other types of algae and the substrate,
which we refer to as `understory.'
We calculate the spawn index in four steps.
First, we develop a statistical framework and sampling protocol to estimate the number of eggs in a given area.
Second, we develop a conversion factor to convert \fishName{} eggs to biomass,
which is critical to calculating the spawn index.
Third, we calculate the spawn index for each of the three aforementioned spawn survey types:
surface, Macrocystis, and understory.
Finally, we combine the spawn indices from the three types of survey observations, and
aggregate by stock assessment region and year to produce
a relative index of combined sex spawning biomass.
We identify uncertainties in spawn index calculations, and
describe how users can install the SpawnIndex \textbf{R} package
to calculate the spawn index using an example database.
Although we transform the spawn survey data from egg density to biomass in tonnes,
the annual time series of egg density and biomass are relative indices of spawning biomass.}

% Resume (i.e., French abstract)
\newcommand{\trResume}{
La série chronologique de l'indice de frai est une composante des évaluations des stocks de hareng du Pacifique (\scienceName{}) en Colombie-Britannique, Canada.
Ce document décrit comment nous calculons l'indice de frai à partir des observations du relevé du frai (par ex., l'étendue spatiale, le nombre de couches d'oeufs, le type de substrat).
Il existe trois types d'observations du relevé des frayères:
(1) les observations des frayères prélevées à la surface habituellement à marée basse;
(2) les observations sous-marines des frayères sur varech géant, Macrocystis (\emph{Macrocystis} spp.); et
(3) les observations sous-marines des frayères sur les autres algues et le substrat, que nous appelons <<sous-étage>>.
Nous calculons l'indice de frai en quatre étapes.
Premièrement, nous élaborons un cadre statistique et un protocole d'échantillonnage pour estimer le nombre d'oeufs dans une zone donnée.
Deuxièmement, nous élaborons un facteur de conversion pour convertir les oeufs de hareng du Pacifique en biomasse, ce qui est essentiel pour calculer l'indice de reproduction.
Troisièmement, nous calculons l'indice de frai pour chacun des trois types de relevés de frai susmentionnés: surface, Macrocystis, et sous-étage.
Enfin, nous combinons les indices de frai des trois types d'observations des relevés, et
nous les agrégeons par région d'évaluation des stocks et par année pour produire un indice relatif de la biomasse reproductrice des sexes combinés.
Nous identifions les incertitudes dans les calculs de l'indice de frai,
et décrivons comment les utilisateurs peuvent installer le paquet \textbf{R} SpawnIndex pour
calculer l'indice de frai en utilisant une base de données d'exemple.
Bien que nous transformions les données du relevé de la densité des oeufs en biomasse en tonnes, les séries chronologiques annuelles de la densité et de la biomasse des oeufs sont des indices relatifs de la biomasse des géniteurs.}

% Label flow diagram steps: surface, Macrocystis, and understory
\newcounter{SurfStep}
\renewcommand{\theSurfStep}{S\arabic{SurfStep}}
\newcounter{MacroStep}
\renewcommand{\theMacroStep}{M\arabic{MacroStep}}
\newcounter{UnderStep}
\renewcommand{\theUnderStep}{U\arabic{UnderStep}}
\newcounter{TotalStep}
\renewcommand{\theTotalStep}{T\arabic{TotalStep}}

\newcommand{\labelSurf}[1]{%
\smash{\raisebox{15pt}{\refstepcounter{SurfStep}\hypertarget{#1}{}\label{#1}}}%
(\theSurfStep)%
}

\newcommand{\labelMacro}[1]{%
\smash{\raisebox{15pt}{\refstepcounter{MacroStep}\hypertarget{#1}{}\label{#1}}}%
(\theMacroStep)%
}

\newcommand{\labelUnder}[1]{%
\smash{\raisebox{15pt}{\refstepcounter{UnderStep}\hypertarget{#1}{}\label{#1}}}%
(\theUnderStep)%
}

\newcommand{\labelTotal}[1]{%
\smash{\raisebox{15pt}{\refstepcounter{TotalStep}\hypertarget{#1}{}\label{#1}}}%
(\theTotalStep)%
}

\newcommand{\surveyManual}{\href{http://www.pac.dfo-mpo.gc.ca/science/species-especes/pelagic-pelagique/herring-hareng/hertags/pdf/SurveyManual.pdf}{\fishName{} spawn survey manual}}

\newcommand{\gitRepo}{\href{https://github.com/grinnellm/SpawnIndex}{\fishName{} spawn index repository}}

%%%%% Start %%%%%

% Start the document
\begin{document}

% R set up
<<init, warning=FALSE, echo=FALSE, message=FALSE>>=
# Load packages
require(tidyverse)
require(bindrcpp)
require(scales)
require(viridis)
require(kableExtra)
require(mapproj)
require(ggrepel)
require(SpawnIndex)
require(gfiscamutils)
require(knitr)
# Omit xcolor warning(s)
knit_hooks$set(document = function(x) {
  sub("\\usepackage[]{color}", "\\usepackage{xcolor}", x, fixed = TRUE)
})
# Suppress summarise info
options(dplyr.summarise.inform = FALSE)
# Change default ggplot theme to 'black and white'
theme_set(theme_bw())
# Modify default theme
herring_theme <- theme(
  legend.box.background = element_rect(fill = alpha("white", 0.7)),
  legend.box.margin = margin(1, 1, 1, 1, "mm"),
  legend.key = element_blank(),
  legend.margin = margin(),
  legend.text.align = 1,
  panel.grid.major = element_line(colour = "darkgrey", size = 0.2),
  panel.grid.minor = element_line(colour = "darkgrey", size = 0.1),
  legend.background = element_rect(fill = "transparent"),
  plot.margin = unit(c(0.1, 0.6, 0.1, 0.1), "lines")
)
# Knitr options
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = "knitr-figs/",
  cache.path = "knitr-cache/",
  echo = FALSE,
  autodep = TRUE,
  cache = TRUE,
  cache.comments = FALSE,
  dev = "png",
  dpi = 600,
  fig.align = "center"
)
# Knitr table options
options(knitr.kable.NA = "")
# Create folder for figures
if (!"knitr-figs" %in% list.files()) dir.create("knitr-figs")
@

<<maps, echo=FALSE>>=
# Region to consider
r_name <- "SoG"
# Location of the saved R image (SoG data summary)
loc_image <- file.path("..", "..", "DataSummaries", r_name)
# Load a saved workspace
load(file = file.path(loc_image, paste("Image.", r_name, ".RData", sep = "")))
# Region name
reg_name_long <- regions %>%
  filter(Region == regName) %>%
  select(RegionName) %>%
  pull()
# All region names
all_regions <- regions %>%
  mutate(FullName = paste(RegionName, " (", Region, ")", sep = ""))
# Major region names
major_regions <- all_regions %>%
  filter(Major) %>%
  select(FullName) %>%
  pull()
# Minor region names
minor_regions <- all_regions %>%
  filter(!Major) %>%
  select(FullName) %>%
  pull()
# Stat Area to examine (character with 2 digits)
zoom_sa <- "14"
# Section to examine (character with 3 digits)
zoom_sec <- "142"
# Buffer for Stat Area map
buff_sa <- 3000
# Buffer for Section map
buff_sec <- 1000
# Year (for spawn index)
yr_index <- 2020
# Calculate spawn summary in current year by location code
spawn_by_loc_xy <- spawnRaw %>%
  filter(Year == yr_index, StatArea == zoom_sa, Section == zoom_sec) %>%
  group_by(LocationCode, LocationName) %>%
  summarise(
    TotalSI = sum_na(c(MacroSI, SurfSI, UnderSI)), Eastings = unique(Eastings),
    Northings = unique(Northings)
  ) %>%
  ungroup() %>%
  arrange(TotalSI)
# Coordinates for Statistical Area map
ext_sa <- shapes$saDF %>%
  filter(id == zoom_sa) %>%
  group_by(id) %>%
  summarise(
    xmin = min(Eastings) - buff_sa, xmax = max(Eastings) + buff_sa,
    ymin = min(Northings) - buff_sa, ymax = max(Northings) + buff_sa
  ) %>%
  ungroup()
# Ratio for Statistical Area figure
xy_ratio_sa <- (ext_sa$ymax - ext_sa$ymin) / (ext_sa$xmax - ext_sa$xmin)
# Determine Sections in the Stat Area
sections_sa <- areas %>%
  filter(StatArea == as.integer(zoom_sa)) %>%
  select(Section) %>%
  distinct() %>%
  mutate(Section = formatC(Section, flag = "0", width = 3)) %>%
  pull(Section)
# Coordinates for Section 142
ext_sec <- shapes$secDF %>%
  filter(id == zoom_sec) %>%
  group_by(id) %>%
  summarise(
    xmin = min(Eastings) - buff_sec, xmax = max(Eastings) + buff_sec,
    ymin = min(Northings) - buff_sec, ymax = max(Northings) + buff_sec
  ) %>%
  ungroup()
# Ratio for Section figure
xy_ratio_sec <- (ext_sec$ymax - ext_sec$ymin) / (ext_sec$xmax - ext_sec$xmin)
# Create a base map for the region
base_map <- ggplot(data = shapes$landCropDF, aes(x = Eastings, y = Northings)) +
  geom_polygon(
    data = shapes$landCropDF, aes(group = group), fill = "darkgrey"
  ) +
  geom_point(data = shapes$extDF, colour = "transparent") +
  coord_equal() +
  labs(x = NULL, y = NULL) +
  scale_x_continuous(labels = function(x) comma(x / 1000), expand = c(0, 0)) +
  scale_y_continuous(labels = function(x) comma(x / 1000), expand = c(0, 0)) +
  herring_theme +
  theme_void() +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 0.5))
@

<<pars, echo=FALSE>>=
# Vector of proportions
prop <- seq(from = 0, to = 1, by = 0.2)
# Vector of plant heights
ht <- seq(from = 2, to = 14, by = 2)
# Vector of number of stalks per plant
stlks <- round(seq(from = 1, to = 23, length.out = 4))
# Load intensity data
data(intensity)
# Intensity and egg layers
intensity <- intensity %>%
  rename(Period9 = Intensity) %>%
  mutate(Period5 = c(1, NA, 2, NA, 3, NA, 4, NA, 5)) %>%
  select(Period5, Period9, Description, Layers) %>%
  arrange(Layers)
# Vector of egg layers (add some at the lower end)
layers <- c(0, 0.05, 0.1, 0.2, 0.35, intensity$Layers)
# Load algae coefficients
data(algae_coefs)
# Algae coefficients
algae_coefs <- algae_coefs %>%
  select(AlgaeName, Coef) %>%
  arrange(AlgaeName)
# Load parameter values
data(pars)
# Load understory width correction factors
data(under_width_facs)
@

%%%% Front matter %%%%%

% Add the first few pages
\frontmatter

%%%%% Drafts %%%%%

\linenumbers  % Line numbers
\renewcommand{\headrulewidth}{0.5pt}  % Header line
\renewcommand{\footrulewidth}{0.5pt}  % Footer line
\fancyhead[c]{Draft: Do not cite or circulate}  % Header text
\setlength{\parskip}{3pt}

%%%%% Main document %%%%%

\section{INTRODUCTION}

Statistical age-structured stock assessment models rely on
an indicator of relative population abundance
to reconstruct a time series of estimated abundance.
For \fishName{} (\scienceName{}) in British Columbia (BC), Canada,
an index of relative population abundance is provided by monitoring the
extent and intensity of spawn (i.e., egg) deposition throughout coastal BC \citeyearpar[DFO][]{DFO2021}.
This document describes our calculations to convert spawn survey observations
(e.g., spatial extent, number of egg layers, substrate type)
to the \fishName{} spawn index in BC.
These calculations have been described elsewhere,
in either published or informal, internal documents.
The objective of this document is to collate the calculations in their order of application.
Spawn index calculations have been updated over the years as more data and analyses justified improvements;
we restrict this document to describing the current method.

\cite{HartTester1934} first demonstrated that an estimate of \fishName{} abundance could be determined by counting egg deposition in a small set of sampling quadrats.
Based on their work, annual spawn surveys collect data used to calculate the spawn index.
There are three types of spawn survey observations:
\begin{enumerate}
\item Observations of spawn taken from the surface usually at low tide,
\item Underwater observations of spawn on giant kelp, Macrocystis (\emph{Macrocystis} spp.), and
\item Underwater observations of spawn on other types of algae and the substrate,
which we refer to as `understory.'
\end{enumerate}
Surface spawn surveys are believed to be the least accurate of the three survey types, but they have the greatest temporal and spatial extent \citep{Schweigert1993b}.
For example, surface spawn surveys were the only survey type prior to \Sexpr{pars$years$dive}, and
they are still used extensively for minor spawns,
remote spawns (i.e., outside stock assessment region boundaries; see below),
unusually early or late spawns, and
during exceptional circumstances such as the COVID-19 pandemic.
Macrocystis and understory spawn surveys are conducted under water using SCUBA gear and
have been used for all major spawns since \Sexpr{pars$years$dive}.
Thus, we describe the spawn index as having two survey periods
based on the predominant survey type:
the surface survey period from \Sexpr{pars$years$assess} to \Sexpr{pars$years$dive-1}, and
the dive survey period from \Sexpr{pars$years$dive} to present.

The introduction of dive surveys in \Sexpr{pars$years$dive} makes it challenging to compare the spawn index between these two periods.
For example, surface surveys are less accurate than dive surveys (\autoref{secWidthSurface}), and
spawn surveyors used subjective intensity categories instead of direct egg layer estimates until \Sexpr{pars$years$layers-1} (\autoref{secIntensity}).
In addition, \fishName{} spawn survey effort has been inconsistent over time due to variation in available resources and departmental priorities.
For example, in the past, surveyors often dedicated several months each year to spawn surveys;
they used small vessels to search for spawn, and surface surveys to estimate egg deposition.
Currently, surveyors use aircraft to search for spawn, and underwater SCUBA surveys to estimate egg deposition.
It typically takes less time to search for spawn using aircraft, and
more effort to measure egg deposition using SCUBA surveys,
Thus, widespread effort (both spatially and temporally) in the past has been replaced with intense effort in the present.
\fishName{} spawn surveys began in \Sexpr{pars$years$survey},
but are considered incomplete for indexing purposes prior to 1937
because many potential areas were not surveyed \citep{HayKronlund1987}.

\fishName{} spawn survey observations have a nested hierarchical structure:
samples, Macrocystis plants, and quadrats are nested within transects,
transects are nested within spawns, and
spawns are nested within Locations.
To develop spawn indices,
Locations are nested within Sections (\autoref{figRegionSec}),
Sections are nested within Statistical Areas (\autoref{figRegionSA}), and
Statistical Areas are nested within stock assessment regions (SARs; \autoref{figRegionReg}).
There are \Sexpr{num_to_word(nrow(regions))} SARs in BC,
which we categorize as either `major' or `minor' (\autoref{figBC}; \citealt{HaistRosenfeld1988}).
The terms `major' and `minor' describe relative differences in geographic and biomass scales.
The major SARs are Haida Gwaii (formerly known as Queen Charlotte Islands), Prince Rupert District (formerly known as North Coast), Central Coast, Strait of Georgia, and West Coast of Vancouver Island.
The minor SARs are \Sexpr{paste_nicely(regions$RegionName[!regions$Major])}.

<<Region>>=
# Number of plots
n_maps <- 3
# Plot Section
map_sec <- base_map +
  geom_path(
    data = filter(shapes$secDF, id %in% zoom_sec), aes(group = Section),
    size = 0.25, colour = "black"
  ) +
  coord_cartesian(
    xlim = c(ext_sec$xmin, ext_sec$xmax),
    ylim = c(ext_sec$ymin, ext_sec$ymax), default = TRUE
  ) +
  geom_point(
    data = spawn_by_loc_xy, aes(colour = TotalSI), size = 3, alpha = 0.5
  ) +
  scale_colour_viridis(labels = comma) +
  labs(colour = "Spawn\nindex (t)") +
  theme(
    legend.justification = c(0, 0), legend.position = c(0.02, 0.02),
    legend.background = element_rect(
      fill = alpha("white", 0.75), colour = "black", size = 0.2
    ),
    panel.border = element_rect(colour = "black", fill = NA, size = 0.5),
    legend.text = element_text(size = 8), legend.title = element_text(size = 8),
    legend.margin = margin(c(4, 4, 4, 4)), legend.key.height = unit(0.3, "cm"),
    legend.text.align = 1, aspect.ratio = xy_ratio_sec
  ) +
  ggsave(
    filename = file.path("knitr-figs", "MapSection.png"), dpi = 600,
    width = figWidth / n_maps, height = figWidth / n_maps * xy_ratio_sec
  )
# Plot Statistical Area
map_sa <- base_map +
  geom_path(
    data = filter(shapes$secDF, id %in% sections_sa), aes(group = Section),
    size = 0.25, colour = "black"
  ) +
  geom_path(
    data = filter(shapes$secDF, id == zoom_sec), aes(group = Section),
    size = 0.75, colour = "black"
  ) +
  geom_label(
    data = filter(shapes$secCentDF, Section %in% sections_sa),
    alpha = 0.75, aes(label = paste("Sec", Section, sep = " ")), size = 3
  ) +
  coord_cartesian(
    xlim = c(ext_sa$xmin, ext_sa$xmax),
    ylim = c(ext_sa$ymin, ext_sa$ymax), default = TRUE
  ) +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 0.5),
    aspect.ratio = xy_ratio_sa
  ) +
  ggsave(
    filename = file.path("knitr-figs", "MapStatArea.png"), dpi = 600,
    width = figWidth / n_maps, height = figWidth / n_maps * xy_ratio_sa
  )
# Plot SAR
map_reg <- base_map +
  geom_path(
    data = shapes$saDF, aes(group = StatArea), size = 0.25, colour = "black"
  ) +
  geom_path(
    data = filter(shapes$saDF, id == zoom_sa), aes(group = StatArea),
    size = 0.75, colour = "black"
  ) +
  geom_label_repel(
    data = shapes$saCentDF, alpha = 0.75,
    aes(label = paste("SA", StatArea, sep = " ")), size = 3
  ) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 0.5)) +
  ggsave(
    filename = file.path("knitr-figs", "MapRegion.png"), dpi = 600,
    width = figWidth / n_maps, height = figWidth / n_maps / shapes$xyRatio
  )
@

\begin{figure}
\centering
\begin{subfigure}[t]{0.32\linewidth}
\includegraphics[width=\linewidth]{knitr-figs/MapSection.png}
\caption{Spawn index in tonnes (t) by Location in Section \Sexpr{zoom_sec}, \Sexpr{regName} SAR.}
\label{figRegionSec}
\end{subfigure}
\hfill
\begin{subfigure}[t]{0.32\linewidth}
\includegraphics[width=\linewidth]{knitr-figs/MapStatArea.png}
\caption{Sections (Sec) in Statistical Area \Sexpr{zoom_sa}, \Sexpr{regName} SAR.}
\label{figRegionSA}
\end{subfigure}
\hfill
\begin{subfigure}[t]{0.32\linewidth}
\includegraphics[width=\linewidth]{knitr-figs/MapRegion.png}
\caption{Statistical Areas (SA) in the \Sexpr{regName} SAR.}
\label{figRegionReg}
\end{subfigure}
\caption[\fishName{} spawn index by Location, as well as Sections and Statistical Areas in the \Sexpr{reg_name_long}]
{\fishName{} spawn index by Location in \Sexpr{yr_index} (\subref{figRegionSec}), Sections (\subref{figRegionSA}), and Statistical Areas (\subref{figRegionReg}) in the \Sexpr{reg_name_long} (\Sexpr{regName}) stock assessment region (SAR; \autoref{figBC}).}
\label{figRegion}
\end{figure}

<<BC, fig.width=figWidth*0.67, fig.height=figWidth/shapes$xyRatio*0.67, fig.lp="fig", echo=FALSE, fig.cap=fig_cap, fig.scap="Spatial boundaries for \\fishName{} stock assessment regions in British Columbia">>=
# Caption
fig_cap <- paste("Spatial boundaries for \\fishName{} stock assessment
                 regions (SARs) in British Columbia. There are ",
  num_to_word(length(major_regions)), " major SARs: ",
  paste_nicely(major_regions), ". There are ",
  num_to_word(length(minor_regions)), " minor SARs: ",
  paste_nicely(minor_regions), ". Units: kilometres (km).",
  sep = ""
)
# Plot BC coast and regions
map_bc <- ggplot(
  data = shapes$landAllCropDF, aes(x = Eastings, y = Northings)
) +
  geom_polygon(
    data = shapes$landAllCropDF, aes(group = group), fill = "darkgrey"
  ) +
  geom_point(data = shapes$extAllDF, colour = "transparent") +
  geom_path(
    data = shapes$regAllDF, aes(group = Region), size = 0.5, colour = "black"
  ) +
  geom_label(
    data = shapes$regCentDF, alpha = 0.5, aes(label = Region), size = 3
  ) +
  annotate(
    geom = "text", x = 1050000, y = 900000,
    label = "British\nColumbia,\nCanada", size = 4
  ) +
  annotate(
    geom = "text", x = 700000, y = 500000,
    label = "Northeast\nPacific\nOcean", size = 4
  ) +
  coord_equal() +
  labs(x = "Eastings (km)", y = "Northings (km)", caption = geoProj) +
  scale_x_continuous(labels = function(x) comma(x / 1000), expand = c(0, 0)) +
  scale_y_continuous(labels = function(x) comma(x / 1000), expand = c(0, 0)) +
  herring_theme +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 0.5))
# Show the figure
print(map_bc)
@

We calculate the spawn index in four main steps.
First, we develop a statistical framework (\autoref{secStat}) and sampling protocol (\autoref{secProt})
to estimate the number of eggs in each spawn.
Second, we develop a conversion factor to convert \fishName{} eggs to spawning biomass (\autoref{secProd}),
which is critical to spawn index calculations.
Third, we calculate the spawn index for each of the three aforementioned spawn survey types:
surface (\autoref{secSurf}),
Macrocystis (\autoref{secMacro}), and
understory (\autoref{secUnder}).
Note that in this report, we use subsections within sections
to separate levels of spatial aggregation
(e.g., calculations at the quadrat, or transect level; \autoref{figFlow}).
Finally, we combine the spawn indices from the three types of survey observations, and
aggregate by SAR and year to produce a relative index of combined sex spawning biomass (\autoref{secTotal}).

\begin{figure}
\centering
\begin{tikzpicture}[node distance=1.0cm and 0.2cm, font=\footnotesize]
\node [terminal, label={[text width=10em] \textbf{Macrocystis (M)}}] (mExt) {\labelMacro{mExt} Determine spatial extent and transect locations (\S{}~\ref{secMacroProt}).};
\node [process, below=of mExt] (mPlant) {\labelMacro{mPlant} Plant $p$ observations for mature plants (e.g., number of stalks; \S{}~\ref{secMacroP}).};
\node [process, below=of mPlant] (mTrans) {\labelMacro{mTrans} Transect $t$ observations and calculations (e.g., spawn width, mean number of egg layers, mean plant height; \S{}~\ref{secMacroT}).};
\node [process, below=of mTrans] (mSpawn) {\labelMacro{mSpawn} Spawn $s$ observations and calculations (e.g., Macrocystis bed length, mean spawn width, mean egg density; \S{}~\ref{secMacroS}).};
\node [inout, below=of mSpawn] (mInd) {\labelMacro{mInd} Macrocystis spawn index $B_{x_{snry}}'$ (Eq~\ref{eqMacroIndS}).};
\node [terminal, label={[text width=10em] \textbf{Surface (S)}}, left=of mExt] (sExt) {\labelSurf{sExt} Determine spatial extent and sample locations (along transects if possible; \S{}~\ref{secSurfProt}).};
\node [process, left=of mPlant] (sSamp) {\labelSurf{sSamp} Sample $j$ observations and calculations (e.g., number of egg layers, substrate type $i$; \S{}~\ref{secSurfJ}).};
\node [process, below=of sSamp, left=of mSpawn] (sSpawn) {\labelSurf{sSpawn} Spawn $s$ observations and calculations (e.g., spawn length, spawn width, mean egg density; \S{}~\ref{secSurfS}).};
\node [inout, below=of sSpawn, left=of mInd] (sInd) {\labelSurf{sInd} Surface spawn index $B_{x_{snry}}'$ (Eq~\ref{eqSurfIndS}).};
\node [terminal, label={[text width=10em] \textbf{Understory (U)}}, right=of mExt] (uExt) {\labelUnder{uExt} Determine spatial extent, transect locations, and quadrat spacing (\S{}~\ref{secUnderProt}).};
\node [process, below=of uExt, right=of mPlant] (uQuad) {\labelUnder{uQuad} Quadrat $q$ observations and calculations (e.g., number of egg layers, algae type $v$; \S{}~\ref{secUnderQ}).};
\node [process, below=of uQuad, right=of mTrans] (uTrans) {\labelUnder{uTrans} Transect $t$ observations and calculations weighted by spawn width (e.g., spawn width, mean egg density; \S{}~\ref{secUnderT}).};
\node [process, below=of uTrans, right=of mSpawn] (uSpawn) {\labelUnder{uSpawn} Spawn $s$ observations and calculations (e.g., algae bed length, mean spawn width, egg density; \S{}~\ref{secUnderS}).};
\node [inout, below=of uSpawn, right=of mInd] (uInd) {\labelUnder{uInd} Understory spawn index $B_{x_{snry}}'$ (Eq~\ref{eqUnderIndS}).};
\node [inout, below=of mInd] (tIndex) {\labelTotal{tIndex} Total spawn index $B_{s_{nry}}'$ (\S{}~\ref{secTotal}, Eq~\ref{eqTotIndSLRY}).};
\draw [line] (mExt) -- (mPlant);
\draw [line] (mPlant) -- (mTrans);
\draw [line] (mTrans) -- (mSpawn);
\draw [line] (mSpawn) -- (mInd);
\draw [line] (mInd) -- (tIndex);
\draw [line] (sExt) -- (sSamp);
\draw [line] (sSamp) -- (sSpawn);
\draw [line] (sSpawn) to (sInd);
\draw [line] (sInd) |- (tIndex);
\draw [line] (uExt) -- (uQuad);
\draw [line] (uQuad) -- (uTrans);
\draw [line] (uTrans) -- (uSpawn);
\draw [line] (uSpawn) -- (uInd);
\draw [line] (uInd) |- (tIndex);
\end{tikzpicture}
\caption[Sequence of steps for \fishName{} spawn index calculations]
{Sequence of steps (e.g., \ref{sExt}) for \fishName{} spawn index calculations for the three spawn survey observation types $x = \{\text{surface, Macrocystis, understory}\}$ (\autoref{tabNotationIndices}).
Legend: rounded rectangles indicate start, rectangles indicate observations and calculations, parallelograms indicate output, arrows show order of operation, `\S{}' indicates section, and `Eq' indicates equation.}
\label{figFlow}
\end{figure}

This document accompanies our SpawnIndex package (\autoref{secPack}).
The SpawnIndex package has functions to calculate the spawn index,
and is a step towards `good enough' practices in scientific computing \citep{WilsonEtal2016}.
Previously, spawn index calculations were implemented in a \textbf{Microsoft Access} database.
We updated the calculations from a database to an \textbf{R} \citeyearpar[RCT][]{R-4.0.5-32} package for several reasons.
First, the database has been used for various purposes over the last two decades
and has incidental calculations that make it overly complex.
Second, the database is difficult to troubleshoot because
it is hard to differentiate between input (i.e., data) and derived values.
Third, the \textbf{R} package is open and transparent;
researchers can view and download the package and an example spawn survey database.
For example, users can run \textbf{R} package functions
to implement calculations described in this document
using a small set of actual observations.
Fourth, we consider it good practice to separate data from analyses.
Fifth, an \textbf{R} package will facilitate future research to quantify spawn index uncertainty.
Finally, an \textbf{R} package will allow us to generate dynamic documents
in the spirit of reproducible research
using \textbf{knitr} \citep{Xie2015, MarwickEtal2018}.

\section{STATISTICAL FRAMEWORK}\label{secStat}

Each spawn survey type has a different statistical framework and sampling protocol (\autoref{secProt}):
surface observations, and
two types of dive observations (Macrocystis and understory).

\subsection{SURFACE SPAWN FRAMEWORK}

Historical and recent surface spawn surveys use an ad hoc sampling regimen,
where surveys are often opportunistic given the state of the tide,
as well as available sampling tools such as boats, rakes, and viewers.
The data are analysed assuming simple random sampling,
which likely generates a biased estimate of mean egg density.

\begin{table}
\centering
\caption[Index notation for \fishName{} spawn index calculations]
{Index notation for \fishName{} spawn index calculations.
Legend: stock assessment region (SAR), spawn-on-kelp (SOK).}
\begin{tabulary}{\linewidth}{lLL}
\toprule
\textbf{Name} & \textbf{Description} & \textbf{Range} \\
\midrule
$y$ & Year & $y_1$, $y_2$, $y_3$, \ldots, $Y$ \\
$Y$ & Last year of time series & \\
$r$ & SAR & 1, 2, 3, \ldots, $R$ \\
$R$ & Number of SARs & \\
$n_{ry}$ & Location & 1, 2, 3, \ldots, $N_{ry}$ \\
$N_{ry}$ & Number of locations & \\
$s_{nry}$ & Spawn & 1, 2, 3, \ldots, $S_{nry}$ \\
$S_{nry}$ & Number of spawns & \\
$x_{snry}$ & Spawn survey type & 1, 2, 3, \ldots, $X_{snry}$ \\
$X_{snry}$ & Number of spawn survey types & \\
$j_{xsnry}$ & Sample & 1, 2, 3, \ldots, $J_{xsnry}$ \\
$J_{xsnry}$ & Number of samples & \\
$i_{jxsnry}$ & Substrate type (surface) & 1, 2, 3, \ldots, $I_{jxsnry}$ \\
$I_{jxsnry}$ & Number of substrate types (surface) & \\
$t_{xsnry}$ & Transect & 1, 2, 3, \ldots, $T_{xsnry}$ \\
$T_{xsnry}$ & Number of transects & \\
$T_{xsnry}'$ & Number of potential transects & \\
$p_{txsnry}$ & Plant & 1, 2, 3, \ldots, $P_{txsnry}$ \\
$P_{txsnry}$ & Number of plants & \\
$k_{ptxsnry}$ & Stalk & 1, 2, 3, \ldots, $K_{ptxsnry}$ \\
$K_{ptxsnry}$ & Number of stalks & \\
$q_{txsnry}$ & Quadrat & 1, 2, 3, \ldots, $Q_{txsnry}$ \\
$Q_{txsnry}$ & Number of quadrats & \\
$Q_{txsnry}'$ & Number of potential quadrats & \\
$i_{qtxsnry}'$ & Substrate type (understory) & 1, 2, 3, \ldots, $I_{qtxsnry}'$ \\
$I_{qtxsnry}'$ & Number of substrate types (understory) & \\
$v_{qtxsnry}$ & Algae (i.e., vegetation) type & 1, 2, 3, \ldots, $V_{qtxsnry}$ \\
$V_{qtxsnry}$ & Number of algae types & \\
$g_{ry}$ & SOK fishery & 1, 2, 3, \ldots, $G_{ry}$ \\
$G_{ry}$ & Number of SOK fisheries & \\
\bottomrule
\end{tabulary}
\label{tabNotationIndices}
\end{table}

\subsection{DIVE SPAWN FRAMEWORK}

In contrast to surface surveys,
underwater dive surveys using SCUBA gear instituted in \Sexpr{pars$years$dive}
follow a two-stage systematic sampling design where
transects are the first sampling stage, and
individual quadrats within transects are the second sampling stage \citep{Jessen1978}.
First we describe the understory spawn framework,
then we describe the Macrocystis spawn framework
which is related to understory, but simpler.

\subsubsection{UNDERSTORY SPAWN FRAMEWORK}

Two steps are required to calculate mean understory egg density in each surveyed spawn $s$ (\autoref{tabNotationIndices}).
First, mean egg density for transect $t$ is
\begin{equation}\label{eqStatRhoT}
\mean{\rho_{t_{xsnry}}} = \frac{1}{Q_{txsnry}} \sum_{q_{txsnry}=1}^{Q_{txsnry}} \rho_{q_{txsnry}},
\end{equation}
where $\rho_q$ is egg density in thousands of eggs per square metre (m) for quadrat $q$ ($10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$),
$Q$ is the number of quadrats (\autoref{tabNotationStat}), and
$\mean{\rho_t}$ is in $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$.
Before we calculate the mean egg density for spawn $s$,
we determine the mean number of potential quadrats in spawn $s$
\begin{equation}\label{eqStatQSPrime}
\mean{Q_{xsnry}'} = \frac{1}{T_{xsnry}} \sum_{t_{xsnry}=1}^{T_{xsnry}} Q_{txsnry}',
\end{equation}
where $Q'$ is the number of potential quadrats
(i.e., a function of spawn width).
Then, we calculate mean egg density in eggs per square metre for spawn $s$
\begin{equation}\label{eqStatRhoS}
\mean{\rho_{s_{nry}}} = \frac{1}{T_{xsnry}\mean{Q_{xsnry}'}}\sum_{t_{xsnry}=1}^{T_{xsnry}} Q_{txsnry}' \mean{\rho_{t_{xsnry}}},
\end{equation}
where $T$ is the number of transects in spawn $s$,
$\mean{Q'}$ is the mean number of potential quadrats from \autoref{eqStatQSPrime},
$Q'$ is the number of potential quadrats,
$\mean{\rho_t}$ is the mean transect egg density from \autoref{eqStatRhoT}, and
$\mean{\rho_s}$ is in $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$.
The egg density estimator from \autoref{eqStatRhoS} is unbiased, and the variance is
\begin{multline}\label{eqStatSigmaS}
\sigma_{s_{nry}}^2 =
\frac{T_{xsnry}'-T_{xsnry}}{T_{xsnry}T_{xsnry}'} \sum_{t_{xsnry}=1}^{T_{xsnry}}
\frac{\left(Q_{txsnry}'\mean{\rho_{t_{xsnry}}}-\mean{Q_{s_{nry}}'}\mean{\rho_{s_{nry}}}\right)^2}
{\mean{Q_{s_{nry}}'}^2\left(T_{xsnry}-1\right)} \\
+ \frac{f_{t_{xsnry}}}{T_{xsnry}^2} \sum_{t_{xsnry}=1}^{T_{xsnry}}
\left(\frac{Q_{txsnry}'}{\mean{Q_{s_{nry}}'}}\right)^2
\frac{\left(1-f_{q_{txsnry}}\right)\sigma_{t_{xsnry}}^2}{Q_{txsnry}},
\end{multline}
where $T'$ is the number of potential transects in spawn $s$ (i.e., a function of spawn length),
$\mean{\rho_t}$ is the mean transect egg density from \autoref{eqStatRhoT},
$\mean{\rho_s}$ is the mean spawn egg density from \autoref{eqStatRhoS},
$f_t$ is the transect sampling fraction for spawn $s$
\begin{equation}\label{eqFT}
f_{t_{xsnry}} = \frac{T_{xsnry}}{T_{xsnry}'},
\end{equation}
$f_q$ is the quadrat sampling fraction for transect $t$
\begin{equation}\label{eqFQ}
f_{q_{txsnry}} = \frac{Q_{txsnry}}{Q_{txsnry}'},
\end{equation}
and
$\sigma_{t}^2$ is the within transect egg density variance
\begin{equation}\label{eqStatSigmaT}
\sigma_{t_{xsnry}}^2 = \frac{1}{{Q_{txsnry}-1}} \sum_{q_{txsnry}=1}^{Q_{txsnry}}
\left(\rho_{q_{txsnry}} - \mean{\rho_{t_{xsnry}}}\right)^2,
\end{equation}
where $\rho_{q}$ is egg density for quadrat $q$, and
$\mean{\rho_{t}}$ is the mean transect egg density from \autoref{eqStatRhoT}.

\begin{table}
\centering
\caption[Notation for \fishName{} spawn survey statistical framework]
{Notation for \fishName{} spawn survey statistical framework.
Legend: metres (m).}
\begin{tabulary}{\linewidth}{lLL}
\toprule
\textbf{Name} & \textbf{Description} & \textbf{Value or unit} \\
\midrule
$\rho$ & Egg density & $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ \\
$\mean{\rho}$ & Mean egg density & $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ \\
$f_t$ & Transect sampling fraction & $0 < f_t \leq 1$ \\
$f_q$ & Quadrat sampling fraction & $0 < f_q \leq 1$ \\
$\sigma^2$ & Egg density variance & $\rho^2$ \\
\bottomrule
\end{tabulary}
\label{tabNotationStat}
\end{table}

The calculation of the mean egg density for each spawn requires estimates of
total spawn length,
mean spawn width,
length of each transect sampled, and
estimated egg density in each sampling quadrat.
The sampling protocol was determined through a series of studies conducted in
the Strait of Georgia in 1981 and 1983 \citep{SchweigertEtal1985, SchweigertEtal1990}, and
on the West Coast of Vancouver Island in 1982 \citep{SchweigertEtal1990}.
In the 1981 study,
the location of transects and sampling quadrats along transects
was determined using random allocation \citep{SchweigertEtal1985}.
However, this proved to be logistically difficult because
neither the spawn length or width is known a priori, and
divers had difficulty making the necessary calculations underwater.
Nevertheless, data from these studies were used to determine a sampling protocol
to estimate mean egg density with standard error of 25\% or less.
The results indicated that the sampling required to achieve this level of precision included
surveying three transects per kilometre of spawn length, and
sampling at least five quadrats per transect (i.e., spawn width).
The sampling design was tested during a 1983 survey in the Strait of Georgia that
applied a systematic rather than a random sampling protocol to simplify the logistics;
variance estimates were similar to those from the 1981 study.
This sampling protocol was further re-evaluated after additional surveys occurred in all areas of the coast during 1984 and 1985;
the protocol was found to be robust and has been in routine use since \Sexpr{pars$years$dive} \citep{SchweigertEtal1990}.
Although samples are collected systematically within each spawn,
we assume that transects and quadrats are located randomly with respect to the underlying spawn distribution,
and so these estimators are applicable \citep{SchaefferEtal2012}.
Systematic sampling has advantages and disadvantages \citep{SchaefferEtal2012}:
advantages include ease of implementation in the field, and more precision in certain situations;
disadvantages include biased estimators when populations are periodic.
An analogous approach has previously been adopted to sample commercial fisheries,
where vessels arrive in port randomly but are sampled systematically
to obtain a random sample \citep{QuinnEtal1983, Sen1984}.

\subsubsection{MACROCYSTIS SPAWN FRAMEWORK}

Giant kelp, Macrocystis (\emph{Macrocystis} spp.),
requires a different framework than the aforementioned understory spawn framework.
Macrocystis plants routinely reach heights of 15~m,
but once weighed down with \fishName{} eggs the plants can sink to lay flat on the substrate.
After sampling \fishName{} eggs on Macrocystis plants,
\citet{HaegeleSchweigert1990} determined that
plant height,
number of fronds per plant, and
number egg layers per plant
were key counts required to estimate the number of eggs per plant.
The survey design employed to capture these data relies on determining the
average plant height,
number of fronds in each plant holdfast, and
number of Macrocystis plants occurring within a 1~m swath
on both sides of the transect line in a given spawn.
These data are used to determine the total egg deposition on Macrocystis plants for each spawn (\autoref{secMacroS}).

\section{SAMPLING PROTOCOL}\label{secProt}

The following is a brief summary of the spawn survey sampling protocol from the \surveyManual{}.
\fishName{} in BC primarily spawn in sheltered bays and inlets,
depositing eggs on rocks and algae between depths of
$1.5\,\text{m}$ above and $18\,\text{m}$ below
the 0-tide level \citep{HumphreysHourston1978, HaegeleSchweigert1985}.
We identify distinct spawns (both spatially and temporally) by a unique combination of year, Location, and `spawn number'
$s_{nry}=1,\,2,\,3,\,\ldots,\,S_{nry}$ (\autoref{tabNotationIndices}).
Spawn numbers identify distinct spawns,
which we define as a continuous stretch of shoreline
with no detectable break in egg deposition;
this is the finest scale at which we calculate the spawn index.
A break in egg deposition is determined by the absence of \fishName{} spawn
on two consecutive transects, or
by a temporal gap in spawning.
Most spawns are also characterized by longitude and latitude,
as well as start and end dates of spawning.
Surveyors usually collect longitude and latitude at the start and end of each transect;
for surface spawn surveys that are not along transects (\autoref{secSurfProt}),
surveyors collect longitude and latitude at the start and end of the spawn
(i.e., overall length and width).

\fishName{} spawns typically extend along the shore;
from above, spawns are identified by a milky or turquoise discolouration of the ocean caused by the release of milt,
and often appear as bands running parallel to the shore (\autoref{figSpawnFlight}).
Thus, spawn `length' refers to distance parallel to the shore, and
`width' refers to distance perpendicular to the shore.
Similarly,
Macrocystis bed length $L'$ and algae (i.e., vegetation) bed length $L''$
refer to distances that Macrocystis and algae beds extend parallel to the shore, respectively.

\begin{figure}
\centering
\fbox{\includegraphics[width=0.67\linewidth]{pictures/SpawnFlight.jpg}}
\caption[Aerial view of \fishName{} spawn]
{Aerial view of \fishName{} spawn taken during a spawn reconnaissance flight in the Strait of Georgia.
Spawn is identified by the band of discoloured water parallel to the shore.}
\label{figSpawnFlight}
\end{figure}

Most areas of the BC coast have `permanent transect' locations recorded on charts which enable surveyors to place transects in the same place each year.
When permanent transects are unavailable for a given spawn,
surveyors set new transects perpendicular to the shore,
beginning $200\,\text{m}$ in from one end of the spawn, and
spaced $350\,\text{m}$ apart along the length of the spawn.
The end of the spawn is determined by the absence of eggs.
We digitize new transects to make them available as permanent transects in subsequent surveys.
Transects generally go from the deep edge of the spawn towards shore
until divers reach the near-shore edge of the spawn;
the near-shore edge can be out of the water depending on the tide height.

\fishName{} spawn surveyors first determine the spatial extent of the spawn in terms of length of shoreline to survey
(\autoref{figFlow}, steps \ref{sExt}, \ref{mExt}, and \ref{uExt});
this is done by raking (\autoref{secSurfProt}) or brief dives to determine the presence or absence of spawn.
Surveyors place the first transect in from one end
(i.e., at the first permanent transect, or $200\,\text{m}$ if there are no permanent transects)
to avoid surveying areas with patchy and sparse egg layers.
Within the spawn area, surveyors use transects to determine
spawn width, quadrat placement, and which Macrocystis plants to survey.
In some cases, we adjust spawn width to improve the accuracy of spawn index estimates (\autoref{secWidthAdjust}).

After determining the spatial extent,
surveyors determine the number of egg layers on substrate and algae
according to sampling protocols described in
\autoref{secSurfProt}, \autoref{secMacroProt}, and \autoref{secUnderProt}.
For eggs on substrate, one egg layer is a layer of eggs one egg thick over the entire spawned surface (\autoref{figLayersSubstrate}).
For eggs on algae, surveyors count egg layers one of two ways depending on whether the algae is flat or round in cross-section.
Egg layers on flat algae are counted on both sides of the algae (\autoref{figLayersAlgaeFlat});
egg layers on round algae are counted across the diameter of the algae (\autoref{figLayersAlgaeRound}).

\begin{figure}
\centering
\begin{subfigure}[t]{0.32\linewidth}
\includegraphics[width=\linewidth]{figures/LayersSubstrate.png}
\caption{Substrate with 1.5 egg layers.}
\label{figLayersSubstrate}
\end{subfigure}
\hfill
\begin{subfigure}[t]{0.32\linewidth}
\includegraphics[width=\linewidth]{figures/LayersAlgaeFlat.png}
\caption{Flat algae with 2.5 egg layers.}
\label{figLayersAlgaeFlat}
\end{subfigure}
\hfill
\begin{subfigure}[t]{0.32\linewidth}
\includegraphics[width=\linewidth]{figures/LayersAlgaeRound.png}
\caption{Round algae with 2.5 egg layers.}
\label{figLayersAlgaeRound}
\end{subfigure}
\caption[Number of \fishName{} egg layers]
{Cross-sections showing the number of \fishName{} egg layers on substrate (\subref{figLayersSubstrate}), flat algae (\subref{figLayersAlgaeFlat}), and round algae (\subref{figLayersAlgaeRound}).
Diagrams copied with permission from the \surveyManual{}.}
\label{figLayers}
\end{figure}

\subsection{SURFACE SPAWN PROTOCOL}\label{secSurfProt}

Surface spawn surveyors use the aforementioned transect interval when possible,
but the sampling interval relies on surveyor judgement and available resources.
If the spawn area is sufficiently large,
surface surveyors usually sample along permanent transects.
Small spawns can still be mapped as they were historically,
with surveyors deciding how to sample the spawn.
To sample, surveyors deploy specialized rakes throughout the spawn to determine algae (i.e., vegetation) type, number of egg layers, and percent cover.
Surveyors may deploy a viewing box in shallow water,
and at low tide a portion of the spawn may be visible for direct observation.
We refer to these surface spawn observations as `samples.'

Recall that there are two cases of surface spawn surveys:
all surveys prior to \Sexpr{pars$years$dive}, and
surveys since \Sexpr{pars$years$dive} when dive surveys are not possible.
Data from surface surveys are combined with data from dive surveys
(i.e., Macrocystis, understory)
to produce the total spawn index (\autoref{secTotal}).

\subsubsection{SPAWN INTENSITY CATEGORIES}\label{secIntensity}

From \Sexpr{pars$years$survey} to \Sexpr{pars$years$layers-1},
surface spawn surveyors categorized spawn by subjective `intensity' categories
instead of direct egg layer estimates (\autoref{tab:Intensity}).
From \Sexpr{pars$years$survey} to \Sexpr{pars$years$nine_cats-1}
there were five intensity categories described as
very light, light, medium, heavy, and very heavy
(numbered 1 to 5, respectively).
Starting in \Sexpr{pars$years$nine_cats} there were nine intensity categories;
the change from five to nine intensity categories was probably to accommodate
the practice of reporting intermediate categories such as 3.5 \citep{HayKronlund1987}.
Starting in \Sexpr{pars$years$layers},
spawn surveyors estimated the number of egg layers directly, and
continued to record intensity categories until 1981
to provide overlap between the two methods.
In addition to recording the number of egg layers,
surveyors sometimes recorded intensity after it was officially discontinued in 1981.
We have converted spawn intensity observations in the \fishName{} spawn survey database from five to nine categories
for spawns that used the five category scale between \Sexpr{pars$years$assess} and \Sexpr{pars$years$nine_cats-1}.
Thus, spawn data used for stock assessments is represented either by a nine category intensity scale, or a direct estimate of the number of egg layers.

<<Intensity>>=
# Caption
tab_cap <- paste("Spawn intensity categories, description, and number of egg
                 layers for \\fishName{} surface spawn surveys for the
                 periods ", pars$years$survey, " to ", pars$years$nine_cats - 1,
                 ", and ", pars$years$nine_cats, " to ", pars$years$layers - 1,
                 " \\citep{HayKronlund1987, SchweigertStocker1988}. Uncertainty
                 in the number of egg layers is not available.",
                 sep = ""
)
# Short caption
tab_s_cap <- "Spawn intensity categories and number of egg layers for
              \\fishName{} surface spawn surveys"
# Column name (5 categories)
p5 <- paste0(pars$years$survey, "--", pars$years$nine_cats - 1)
# Column name (9 categories)
p9 <- paste0(pars$years$nine_cats, "--", pars$years$layers - 1)
# Format the table
k_intensity <- intensity %>%
  arrange(Layers) %>%
  rename(!!p5 := Period5, !!p9 := Period9, `Number of egg layers` = Layers) %>%
  kable(
    caption = tab_cap, caption.short = tab_s_cap, booktabs = TRUE, linesep = "",
    escape = FALSE
  ) %>%
  row_spec(0, bold = TRUE) %>%
  add_header_above(header = c("Intensity category" = 2, "", ""), bold = TRUE)
# Print the table
k_intensity
@

\subsection{MACROCYSTIS SPAWN PROTOCOL}\label{secMacroProt}

Macrocystis spawn surveyors take a census of Macrocystis plants
within $1\,\text{m}$ of the transect line,
on both the left- and right-hand sides.
We refer to the swath of substrate along Macrocystis transects as the transect swath,
$\chi_t = 2\,\text{m}$ in transect $t$.
Divers categorize Macrocystis plants as either `mature' or `immature' based on stipe height;
mature plants have stipes $\geq 1\,\text{m}$ high, and are the only plants used for Macrocystis spawn index calculations.
Immature plants are excluded because \fishName{} spawn on Macrocystis fronds, not stipes;
immature plants have limited fronds and slimy stipes that prevent egg adhesion.
In addition, \fishName{} typically deposit spawn higher up Macrocystis plants.
For each mature plant, divers record the number of stalks.
For each transect, divers record the average number of egg layers, and average plant height.
\cite{HaegeleSchweigert1990} provide a description of the sampling technique, and the basis for estimating the total number of eggs per plant.

\subsection{UNDERSTORY SPAWN PROTOCOL}\label{secUnderProt}

Understory spawn surveyors place quadrats along transects, with a target frequency of $\geq 5$ quadrats per transect,
given a minimum spacing of $2\,\text{m}$ and
a maximum spacing of $40\,\text{m}$.
Similar to how the first transect is moved in from one end of the spawn,
the first quadrat is moved in from the edge of the spawn to the first $5\,\text{m}$ mark on the transect line
to avoid surveying areas with patchy and sparse egg layers.
Note that quadrat position along permanent transects varies among years
due to the location and extent (i.e., width) of spawn with respect to the shoreline:
spawn location causes quadrats to shift seaward or shoreward, and
spawn width causes transects to be shorter or longer.
Understory spawn surveys use $0.5\,\text{m}^2$ quadrats;
other sizes (e.g., $0.25$ and $1.0\,\text{m}^2$) have been used for research,
but are not used to calculate the spawn index \citep{Schweigert1993b}.
Within each quadrat, divers record
the dominant (i.e., most heavily spawned) substrate type,
percentage of the quadrat covered by spawn, and
number of egg layers.
In addition, divers identify the three most abundant algae types that have spawn.
For each of these algae types, divers record the percentage of the quadrat covered by the algae and number of egg layers.

\section{CONVERTING EGGS TO BIOMASS}\label{secProd}

After estimating the number of eggs in a spawn by survey observation type,
the next step is to estimate the biomass of \fishName{} that spawned.
Female \fishName{} produce an average of approximately $200\,000$ eggs per kilogram (kg) of total body weight \citep{Hay1985};
we refer to this as fecundity.
Average fecundity is derived from studies of
BC \fishName{} in 1974 and 1980 (Prince Rupert District, Strait of Georgia, and West Coast of Vancouver Island; \citealp{Hay1985}), and
California \fishName{} in 1975 \citep{RabinBarnhart1977}.
We assume that females account for 50\% of spawners,
and we convert eggs to tonnes (t) of spawners using
\begin{equation}\label{eqECF}
\theta = \omega \female \frac{10^3~\text{kg}} {\text{t}},
\end{equation}
where $\omega$ is female fecundity,
$\female$ is the proportion of spawners that are female, and
$\theta$ is the egg conversion factor in $10^8 \cdot \text{eggs} \cdot \text{t}^{-1}$ (\autoref{tabNotationEggs}).
Thus, we convert eggs to biomass of both sexes combined in tonnes by dividing the number of eggs by $\theta$.
Although \fishName{} egg production is affected by environmental variability and other factors \citep{TanasichukWare1987, HayBrett1988},
we assume that bias to the spawn index from \autoref{eqECF}
is insignificant in most areas and years \citep{Ware1985, Schweigert1993b}.

\begin{table}
\centering
\caption[Notation for converting \fishName{} eggs to spawning biomass]
{Notation for converting the number of \fishName{} eggs to spawning biomass.
Legend: kilograms (kg), tonnes (t).}
\begin{tabulary}{\linewidth}{lLLL}
\toprule
\textbf{Name} & \textbf{Description} & \textbf{Value or unit} & \textbf{References} \\
\midrule
$\omega$ & Female fecundity & \Sexpr{format(pars$conversion$omega, big.mark=",", scientific=FALSE)}$~\text{eggs} \cdot \text{kg}^{-1}$ & \cite{Hay1985, HayBrett1988} \\
$\female$ & Proportion female & \Sexpr{pars$conversion$female} & \\
$\theta$ & Egg conversion factor & $10^8 \cdot \text{eggs} \cdot \text{t}^{-1}$ & \\
\bottomrule
\end{tabulary}
\label{tabNotationEggs}
\end{table}

\section{SURFACE SPAWN CALCULATIONS}\label{secSurf}

This section describes steps \ref{sSamp} to \ref{sInd} (\autoref{figFlow}).
As previously mentioned, surface spawn surveyors sample along transects or using their judgement (\autoref{secSurfProt}).
Surveyors collect data at the substrate type $i$, sample $j$, and spawn $s$ levels;
we calculate metrics at the substrate type $i$, sample $j$, and spawn $s$ levels
(\autoref{tabNotationIndices} and \autoref{tabNotationSurf}).
We use the term `metric' to refer to a measure of quantitative assessment.
Recall that surface spawn `samples' include observations collected using specialized rakes and viewing boxes (\autoref{secSurfProt}).
Occasionally, we use field data sheets to fill-in missing egg layer information for surface survey data (\autoref{secUpdate}).

\begin{table}
\centering
\caption[Notation for \fishName{} surface spawn index calculations]
{Notation for \fishName{} surface spawn index calculations.
Legend: metres (m), tonnes (t).}
\begin{tabulary}{\linewidth}{lLLL}
\toprule
\textbf{Name} & \textbf{Description} & \textbf{Value or unit} & \textbf{References} \\
\midrule
$E'$ & Number of egg layers & $E' > 0$ & \\
$\phi$ & Proportion covered in eggs & $0 < \phi \leq 1$ & \\
$E$ & Number of egg layers & $E > 0$ & \\
$\alpha$ & Regression intercept & \Sexpr{pars$surface$alpha}$~10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ & \cite{SchweigertEtal1997} \\
$\beta$ & Regression slope & \Sexpr{pars$surface$beta}$~10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ & \cite{SchweigertEtal1997} \\
$\rho$ & Egg density & $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ & \\[0.5ex]
$\mean{\rho}$ & Mean egg density & $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ &  \\
$L$ & Spawn length & m & \\
$W$ & Spawn width & m & \\
$B'$ & Surface spawn index (i.e., biomass) & t & \\
\bottomrule
\end{tabulary}
\label{tabNotationSurf}
\end{table}

\subsection{SAMPLE OBSERVATIONS AND CALCULATIONS}\label{secSurfJ}

Each sample $j$ (\autoref{figFlow}, step \ref{sSamp}) can have one or more substrate types $i$.
The number of egg layers in substrate $i$ is
\begin{equation}\label{eqSurfLayersIJS}
E_{i_{jxsnry}} = E_{i_{jxsnry}}' \phi_{i_{jxsnry}},
\end{equation}
where $E_i'$ is the number of egg layers on substrate $i$,
$\phi_i$ is the proportion of substrate $i$ covered with spawn, and
$E_i$ is in number of egg layers.
The total number of egg layers in sample $j$ is
\begin{equation}\label{eqSurfLayersJS}
E_{j_{xsnry}} = \sum_{i_{jxsnry}=1}^{I_{jxsnry}} E_{i_{jxsnry}},
\end{equation}
where $E_i$ is the number of egg layers in substrate $i$ from \autoref{eqSurfLayersIJS}, and
$E_j$ is in number of egg layers.
For the time period when surveyors recorded spawn `intensity' categories instead of direct egg layer estimates,
we convert intensity to number of egg layers $E_j$ (\autoref{tab:Intensity}).
\citet{SchweigertEtal1997} developed a model of surface egg density as a function of number of egg layers using a linear regression model%
\footnote{There is an error in \cite{SchweigertEtal1997};
surface egg density is in thousands per square metre ($10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$).
Likewise, we report eggs in thousands (i.e., $10^3 \cdot \text{eggs}$) in this document and in the \textbf{R} package.}
\begin{equation}\label{eqSurfDensJS}
\rho_{j_{xsnry}} = \alpha + \beta E_{j_{xsnry}},
\end{equation}
where $\alpha$ is the regression intercept,
$\beta$ is the regression slope,
$E_j$ is the total number of egg layers in sample $j$ from \autoref{eqSurfLayersJS}, and
$\rho_j$ is in $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ (\autoref{figSurfDensJS}).
Note that $E_j = 0 \Rightarrow \rho_j = 0$ to avoid having $\rho_j = \alpha$ when there are no egg layers (i.e., $E_j = 0$).

<<SurfDensJS, fig.width=3.5, fig.asp=0.67, fig.lp="fig", echo=FALSE, fig.cap=fig_cap, fig.scap="Egg density for \\fishName{} surface spawn surveys">>=
# Caption
fig_cap <- paste("Relationship between egg density in thousands of eggs per
                 square metre (m; line), and number of egg layers for
                 \\fishName{} surface spawn surveys based on
                 \\autoref{eqSurfDensJS} \\citep{SchweigertEtal1997}. Note that
                 number of egg layers can exceed those shown in this figure.")
# Expand the values
df <- expand.grid(Layers = layers)
# Make a table of egg layers, proportion, and egg density
dat <- as_tibble(df) %>%
  mutate(EggDens = dens_surf(egg_layers = Layers))
# Figure
egg_dens_sub_plot <- ggplot(
  data = dat, mapping = aes(x = Layers, y = EggDens)
) +
  geom_line() +
  labs(
    x = "Number of egg layers",
    y = expression(paste("Egg density (", 10^3 %.% "eggs" %.% "m"^-2, ")",
      sep = ""
    ))
  ) +
  scale_y_continuous(labels = comma) +
  expand_limits(x = 0, y = 0) +
  herring_theme
# Show the figure
print(egg_dens_sub_plot)
@

\subsection{SPAWN OBSERVATIONS AND CALCULATIONS}\label{secSurfS}

The mean egg density in spawn $s$ (\autoref{figFlow}, step \ref{sSpawn}) is
\begin{equation}\label{eqSurfDensS}
\mean{\rho_{s_{nry}}} = \frac{1}{J_{xsnry}} \sum_{j_{xsnry}=1}^{J_{xsnry}} \rho_{j_{xsnry}},
\end{equation}
where $\rho_j$ is egg density in sample $j$ from \autoref{eqSurfDensJS},
$J$ is the number of samples, and
$\mean{\rho_s}$ is in $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$.
Two other metrics are required at the spawn level:
spawn length $L_s$, and
spawn width $W_s$, both in metres.
We set $W_s$ to the first non-missing value of
median pool width, median Section width, median SAR width, or observed width $W_s'$
(in that order; \autoref{secWidthSurface}).
A pool is a group of Locations within a Section that are
often adjacent,
contain similar algae and substrate, and
can be treated as a group with likely similar widths.

The surface spawn index in spawn $s$ is
\begin{equation}\label{eqSurfIndS}
B_{s_{nry}}' = \frac{\mean{\rho_{s_{nry}}} L_{s_{nry}} W_{s_{nry}} 10^3} {\theta},
\end{equation}
where $\mean{\rho_s}$ is mean egg density in spawn $s$ from \autoref{eqSurfDensS},
$L_s$ is length of spawn $s$,
$W_s$ is width of spawn $s$,
$\theta$ is the egg conversion factor from \autoref{eqECF}, and
$B_s'$ is in tonnes (\autoref{figFlow}, step \ref{sInd}).

\section{MACROCYSTIS SPAWN CALCULATIONS}\label{secMacro}

This section describes steps \ref{mPlant} to \ref{mInd} (\autoref{figFlow}).
Macrocystis spawn surveyors use SCUBA gear to collect underwater data for individual plants $p$, transects $t$, and spawns $s$ (\autoref{secMacroProt});
we calculate metrics at the transect $t$, and spawn $s$ levels
(\autoref{tabNotationIndices} and \autoref{tabNotationMacro}).
Recall that divers enumerate every Macrocystis plant within the transect swath.

\begin{table}
\centering
\caption[Notation for \fishName{} Macrocystis spawn index calculations]
{Notation for \fishName{} Macrocystis spawn index calculations.
Legend: metres (m), tonnes (t).}
\begin{tabulary}{\linewidth}{lLLL}
\toprule
\textbf{Name} & \textbf{Description} & \textbf{Value or unit} & \textbf{References} \\
\midrule
$W$ & Spawn width & m & \\
$\chi$ & Transect swath & m & \\
$A$ & Area & $\text{m}^2$ & \\
$\mean{W}$ & Mean spawn width & m & \\
$\mean{H}$ & Mean plant height & m & \\
$\mean{E}$ & Mean number of egg layers & $\mean{E} > 0$ & \\
$L'$ & Length of the Macrocystis bed & m & \\
$L$ & Spawn length & m & \\
$\mean{\kappa}$ & Mean number of stalks per plant & $\mean{\kappa} > 0$ & \\
$\xi$ & Regression slope & \Sexpr{pars$macrocystis$xi}$~\text{eggs} \cdot 10^3 \cdot \text{plant}^{-1}$ & \cite{HaegeleSchweigert1990} \\
$\gamma$ & Regression exponent on $\mean{E}$ & \Sexpr{pars$macrocystis$gamma} & \cite{HaegeleSchweigert1990} \\
$\delta$ & Regression exponent on $\mean{H}$ & \Sexpr{pars$macrocystis$delta} & \cite{HaegeleSchweigert1990} \\
$\epsilon$ & Regression exponent on $\mean{\kappa}$ & \Sexpr{pars$macrocystis$epsilon} & \cite{HaegeleSchweigert1990} \\
$\mean{\psi}$ & Mean number of eggs per plant & $\text{eggs} \cdot 10^3 \cdot \text{plant}^{-1}$ & \\
$\mean{\rho}$ & Mean egg density & $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ & \\
$B'$ & Macrocystis spawn index (i.e., biomass) & t & \\
\bottomrule
\end{tabulary}
\label{tabNotationMacro}
\end{table}

\subsection{PLANT OBSERVATIONS}\label{secMacroP}

For each mature plant $p$ (\autoref{figFlow}, step \ref{mPlant}),
surveyors count the number of stalks $K_p$.

\subsection{TRANSECT OBSERVATIONS AND CALCULATIONS}\label{secMacroT}

At the transect $t$ level (\autoref{figFlow}, step \ref{mTrans}),
spawn width is $W_t$, and
transect swath is $\chi_t = 2\,\text{m}$, both in metres.
We calculate the area in transect $t$ as
\begin{equation}\label{eqMacroAreaTS}
A_{t_{xsnry}} = W_{t_{xsnry}} \chi_{t_{xsnry}}
\end{equation}
in square metres.
In addition, divers estimate summary statistics for mature Macrocystis plants $p$ along transect $t$:
mean height $\mean{H_{t_{xsnry}}}$ in metres, and
mean number of egg layers $\mean{E_{t_{xsnry}}}$.
We calculate the total number of stalks $K$ in transect $t$ as
\begin{equation}\label{eqMacroStalksTS}
K_{t_{xsnry}} = \sum_{p_{txsnry}=1}^{P_{txsnry}} K_{p_{txsnry}},
\end{equation}
where $K_p$ is the number of stalks on plant $p$, and
$K_t$ is in number of stalks.

\subsection{SPAWN OBSERVATIONS AND CALCULATIONS}\label{secMacroS}

At the spawn $s$ level (\autoref{figFlow}, step \ref{mSpawn}),
the Macrocystis bed length is $L_s'$ in metres.
If $L_s'$ is inadvertently not recorded,
we set $L_s'$ to the spawn length $L_s$.
The mean width of spawn $s$ is
\begin{equation}\label{eqMacroWidthS}
\mean{W_{s_{nry}}} = \frac{1}{T_{xsnry}} \sum_{t_{xsnry}=1}^{T_{xsnry}} W_{t_{xsnry}},
\end{equation}
where $W_t$ is the spawn width at transect $t$,
$T$ is the number of transects in spawn $s$, and
$\mean{W_s}$ is in metres.
The total area of transects in spawn $s$ is
\begin{equation}\label{eqMacroAreaS}
A_{s_{nry}} = \sum_{t_{xsnry}=1}^{T_{xsnry}} A_{t_{xsnry}},
\end{equation}
where $A_t$ is the transect area from \autoref{eqMacroAreaTS},
and $A_s$ is in square metres.

Three metrics are required to calculate the number of eggs on Macrocystis plants \citep{HaegeleSchweigert1990}:
number of egg layers,
plant height, and
number of stalks per plant.
First, the mean number of egg layers in spawn $s$ is
\begin{equation}\label{eqMacroLayersS}
\mean{E_{s_{nry}}} = \frac{1}{T_{xsnry}} \sum_{t_{xsnry}=1}^{T_{xsnry}} \mean{E_{t_{xsnry}}},
\end{equation}
where $\mean{E_t}$ is the mean number of egg layers in transect $t$,
$T$ is the number of transects in spawn $s$, and
$\mean{E_s}$ is in number of egg layers.
Second, the mean plant height in spawn $s$ is
\begin{equation}\label{eqMacroHeightS}
\mean{H_{s_{nry}}} = \frac{1}{T_{xsnry}} \sum_{t_{xsnry}=1}^{T_{xsnry}} \mean{H_{t_{xsnry}}},
\end{equation}
where $\mean{H_t}$ is the mean plant height in transect $t$,
$T$ is the number of transects in spawn $s$, and
$\mean{H_s}$ is in metres.
The third metric is the number of stalks per plant,
which we calculate in three steps.
The total number of observed stalks in spawn $s$ is
\begin{equation}\label{eqMacroStalksS}
K_{s_{nry}} = \sum_{t_{xsnry}=1}^{T_{xsnry}} K_{t_{xsnry}},
\end{equation}
where $K_t$ is the number of stalks in transect $t$ from \autoref{eqMacroStalksTS},
$T$ is the number of transects in spawn $s$, and
$K_s$ is in number of stalks.
The total number of observed plants in spawn $s$ is
\begin{equation}\label{eqMacroPlantsS}
P_{s_{nry}} = \sum_{t_{xsnry}=1}^{T_{xsnry}} P_{t_{xsnry}},
\end{equation}
where $P_t$ is the number of plants in transect $t$,
$T$ is the number of transects in spawn $s$, and
$P_s$ is in number of plants.
Thus, the mean number of stalks per plant in spawn $s$ is
\begin{equation}\label{eqMacroStalksPerPlantS}
\mean{\kappa_{s_{nry}}} = \frac{K_{s_{nry}}}{P_{s_{nry}}},
\end{equation}
where $K_s$ is the number of stalks in spawn $s$ from \autoref{eqMacroStalksS},
$P_s$ is the number of plants in spawn $s$ from \autoref{eqMacroPlantsS},
and $\mean{\kappa_s}$ is in number of stalks per plant.

\citet{HaegeleSchweigert1990} developed a model of the number of eggs per plant
as a function of the three aforementioned metrics
(number of egg layers, plant height, and number of stalks per plant)
using a nonlinear multiple regression model
\begin{equation}\label{eqMacroEggsPerPlantS}
\mean{\psi_{s_{nry}}} = \xi \mean{E_{s_{nry}}}^\gamma \mean{H_{s_{nry}}}^\delta \mean{\kappa_{s_{nry}}}^\epsilon 10^3,
\end{equation}
where $\xi$ is the regression slope,
$\mean{E_s}$ is the mean number of egg layers in spawn $s$ from \autoref{eqMacroLayersS},
$\gamma$ is the regression exponent on $\mean{E_s}$,
$\mean{H_s}$ is the mean plant height in spawn $s$ from \autoref{eqMacroHeightS},
$\delta$ is the regression exponent on $\mean{H_s}$,
$\mean{\kappa_s}$ is the mean number of stalks per plant in spawn $s$ from \autoref{eqMacroStalksPerPlantS},
$\epsilon$ is the regression exponent on $\mean{\kappa_s}$, and
$\mean{\psi_s}$ is in $\text{eggs} \cdot 10^3 \cdot \text{plant}^{-1}$ (\autoref{figMacroEggsPerPlantS}).
Mean Macrocystis egg density in spawn $s$ is
\begin{equation}\label{eqMacroDensS}
\mean{\rho_{s_{nry}}} = \frac{\mean{\psi_{s_{nry}}} P_{s_{nry}}}{A_{s_{nry}}},
\end{equation}
where
$\mean{\psi_s}$ is the mean number of eggs per plant in spawn $s$ from \autoref{eqMacroEggsPerPlantS},
$P_s$ is the number of plants in spawn $s$ from \autoref{eqMacroPlantsS},
$A_s$ is the total area of transects in spawn $s$ from \autoref{eqMacroAreaS}, and
$\mean{\rho_s}$ is in $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$.

The Macrocystis spawn index in spawn $s$ is
\begin{equation}\label{eqMacroIndS}
B_{s_{nry}}' = \frac{\mean{\rho_{s_{nry}}} L_{s_{nry}}' \mean{W_{s_{nry}}} 10^3} {\theta},
\end{equation}
where $\mean{\rho_s}$ is the mean egg density in spawn $s$ from \autoref{eqMacroDensS},
$L_s'$ is the length of the Macrocystis bed in spawn $s$,
$\mean{W_s}$ is the mean width of spawn $s$ from \autoref{eqMacroWidthS},
$\theta$ is the egg conversion factor from \autoref{eqECF}, and
$B_s'$ is in tonnes (\autoref{figFlow}, step \ref{mInd}).

<<MacroEggsPerPlantS, fig.width=6, fig.asp=0.9, fig.lp="fig", echo=FALSE, fig.cap=fig_cap, fig.scap="Number of eggs per plant for \\fishName{} Macrocystis spawn surveys">>=
# Caption
fig_cap <- paste("Relationship between number of eggs in thousands per
                 Macrocystis plant (lines), and number of egg layers on plants,
                 plant height in metres (m), and number of stalks per plant for
                 \\fishName{} Macrocystis spawn surveys based on
                 \\autoref{eqMacroEggsPerPlantS} \\citep{HaegeleSchweigert1990}.
                 Note that number of egg layers, plant height, and number of
                 stalks per plant can exceed those shown in this figure.")
# Expand the values
df <- expand.grid(Layers = layers, PlantHeight = ht, Stalks = stlks)
# Make a table of egg layers, proportion, coefficient, and egg density
dat <- as_tibble(df) %>%
  mutate(
    Number = eggs_macro(
      egg_layers = Layers, height = PlantHeight, stalks_per_plant = Stalks
    ),
    Stalks = paste("Number of stalks per plant: ",
      formatC(Stalks, width = 2, flag = "0"),
      sep = ""
    )
  )
# Figure
num_egg_plot <- ggplot(
  data = dat, mapping = aes(x = Layers, y = Number, group = PlantHeight)
) +
  geom_line(mapping = aes(colour = PlantHeight)) +
  labs(
    x = "Number of egg layers on plants",
    y = expression(paste("Number of eggs per plant (",
      10^3 %.% "eggs" %.% "plant"^-1, ")",
      sep = ""
    )),
    colour = "Plant height (m)"
  ) +
  scale_y_continuous(labels = comma) +
  scale_colour_viridis() +
  facet_wrap(Stalks ~ ., ncol = 2) +
  expand_limits(x = 0, y = 0) +
  herring_theme +
  theme(legend.position = "top")
# Show the figure
print(num_egg_plot)
@

\section{UNDERSTORY SPAWN CALCULATIONS}\label{secUnder}

This section describes steps \ref{uQuad} to \ref{uInd} (\autoref{figFlow}).
Understory spawn surveyors use SCUBA gear to collect underwater data for
substrate $i'$, algae (i.e., vegetation) types $v$, quadrats $q$, transects $t$, and spawns $s$ (\autoref{secUnderProt});
we calculate metrics at the substrate $i'$, algae type $v$, quadrat $q$, transect $t$, and spawn $s$ levels
(\autoref{tabNotationIndices} and \autoref{tabNotationUnder}).
Recall that divers collect understory observations in quadrats, which are distributed along transects.

\begin{table}
\centering
\caption[Notation for \fishName{} understory spawn index calculations]
{Notation for \fishName{} understory spawn index calculations.
Legend: metres (m), tonnes (t).}
\begin{tabulary}{\linewidth}{lLLL}
\toprule
\textbf{Name} & \textbf{Description} & \textbf{Value or unit} & \textbf{References} \\
\midrule
$\varphi$ & Regression slope for substrate & \Sexpr{pars$understory$varphi}$~10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ & \cite{HaegeleEtal1979} \\
$E$ & Number of egg layers & $E > 0$ & \\
$\phi$ & Proportion covered in eggs & $0 < \phi \leq 1$ & \\
$\rho$ & Egg density & $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ & \\
$\vartheta$ & Regression slope for algae & \Sexpr{pars$understory$vartheta}$~10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ & \cite{Schweigert2005} \\
$\varrho$ & Regression exponent on $E$ & \Sexpr{pars$understory$varrho} & \cite{Schweigert2005} \\
$\varsigma$ & Regression exponent on $\phi$ & \Sexpr{pars$understory$varsigma} & \cite{Schweigert2005} \\
$C$ & Algae coefficient & see \autoref{tab:AlgaeCoefs} & \\
$W$ & Spawn width & m & \\
$\mean{\rho}$ & Mean egg density & $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ & \\
$\mean{W}$ & Mean spawn width & m & \\
$L''$ & Length of the algae bed & m & \\
$L$ & Spawn length & m & \\
$B'$ & Understory spawn index (i.e., biomass) & t & \\
\bottomrule
\end{tabulary}
\label{tabNotationUnder}
\end{table}

\subsection{QUADRAT OBSERVATIONS AND CALCULATIONS}\label{secUnderQ}

We calculate two separate estimates of egg density at the quadrat level (\autoref{figFlow}, step \ref{uQuad}):
spawn on substrate $i'$, and spawn on algae $v$.
\citet{HaegeleEtal1979} developed a model of substrate egg density in quadrat $q$, transect $t$, and spawn $s$ from egg layers using a linear model
\begin{equation}\label{eqUnderDensSubQTS}
\rho_{i_{qtxsnry}'} = \varphi E_{i_{qtxsnry}'} \phi_{i_{qtxsnry}'},
\end{equation}
where $\varphi$ is the slope,
$E_{i'}$ is the number of egg layers on substrate $i'$,
$\phi_{i'}$ is the proportion of substrate $i'$ covered by spawn, and
$\rho_{i'}$ is substrate egg density in $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ (\autoref{figUnderDensSubQTS}).

<<UnderDensSubQTS, fig.width=3.5, fig.asp=0.85, fig.lp="fig", echo=FALSE, fig.cap=fig_cap, fig.scap="Substrate egg density for \\fishName{} underwater spawn surveys">>=
# Caption
fig_cap <- paste("Relationship between substrate egg density in thousands of
                 eggs per square metre (m; lines), and number of egg layers on
                 substrate and proportion of substrate covered in spawn for
                 \\fishName{} underwater spawn surveys based on
                 \\autoref{eqUnderDensSubQTS} \\citep{HaegeleEtal1979}. Note
                 that number of egg layers can exceed those shown in this
                 figure.")
# Expand the values
df <- expand.grid(Layers = layers, Proportion = prop)
# Make a table of egg layers, proportion, and egg density
dat <- as_tibble(df) %>%
  mutate(EggDens = dens_under_sub(
    egg_layers = Layers, proportion = Proportion
  ))
# Figure
egg_dens_sub_plot <- ggplot(
  data = dat, mapping = aes(x = Layers, y = EggDens, group = Proportion)
) +
  geom_line(mapping = aes(colour = Proportion)) +
  labs(
    x = "Number of egg layers on substrate",
    y = expression(paste("Substrate egg density (",
      10^3 %.% "eggs" %.% "m"^-2, ")",
      sep = ""
    )),
    colour = "Proportion of substrate\ncovered in spawn"
  ) +
  scale_y_continuous(labels = comma) +
  scale_colour_viridis() +
  expand_limits(x = 0, y = 0) +
  herring_theme +
  theme(legend.position = "top")
# Show the figure
print(egg_dens_sub_plot)
@

Although quadrats have only one substrate type,
they can have up to three algae types $v$ (\autoref{secUnderProt}).
\citet{Schweigert2005} developed a model of algae egg density from
egg layers,
proportion of the quadrat covered by algae, and
algae coefficients using a generalized linear model.
Algae coefficients account for the effect of algae morphology
on \fishName{} egg density (\autoref{tab:AlgaeCoefs}).
Egg density on algae $v$ in quadrat $q$, transect $t$, and spawn $s$ \citep{Schweigert2005} is
\begin{equation}\label{eqUnderDensAlgVQTS}
\rho_{v_{qtxsnry}} = \vartheta E_{v_{qtxsnry}}^\varrho \phi_{v_{qtxsnry}}^\varsigma C_v,
\end{equation}
where $\vartheta$ is the regression slope,
$E_v$ is the number of egg layers on algae $v$,
$\varrho$ is the regression exponent on $E_v$,
$\phi_v$ is the proportion of quadrat $q$ covered by algae $v$,
$\varsigma$ is the regression exponent on $\phi_v$,
$C_v$ is the coefficient for algae $v$, and
$\rho_v$ is in $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$ (\autoref{figUnderDensAlgVQTS}).

<<AlgaeCoefs>>=
# Caption
tab_cap <- "Algae (i.e., vegetation) types $v$ and coefficients $C$ for
            \\fishName{} understory spawn surveys \\citep{Schweigert2005}.
            Uncertainty in algae coefficients is not available. Algae types are
            described in the \\surveyManual{}."
# Short caption
tab_s_cap <- "Algae types and coefficients for \\fishName{} understory spawn
              surveys"
# Format the table
k_algae_coefs <- algae_coefs %>%
  rename(`Algae type $v$` = AlgaeName, `Coefficient $C$` = Coef) %>%
  kable(
    caption = tab_cap, caption.short = tab_s_cap, booktabs = TRUE, linesep = "",
    escape = FALSE
  ) %>%
  row_spec(0, bold = TRUE)
# Print the table
k_algae_coefs
@

<<UnderDensAlgVQTS, fig.width=6, fig.asp=1.1, fig.lp="fig", echo=FALSE, fig.cap=fig_cap, fig.scap="Algae egg density for \\fishName{} underwater spawn surveys">>=
# Caption
fig_cap <- paste("Relationship between algae egg density in thousands of eggs
                 per square metre (m; lines), and number of egg layers on algae,
                 proportion of substrate covered in algae, and algae coefficient
                 (\\autoref{tab:AlgaeCoefs}) for \\fishName{} underwater spawn
                 surveys based on  \\autoref{eqUnderDensAlgVQTS}
                 \\citep{Schweigert2005}. Note that number of egg layers can
                 exceed those shown in this figure.")
# Expand the values
df <- expand.grid(
  Layers = layers, Proportion = prop, Coefficient = unique(algae_coefs$Coef)
)
# Make a table of egg layers, proportion, coefficient, and egg density
dat <- as_tibble(df) %>%
  arrange(Coefficient) %>%
  mutate(
    EggDens = dens_under_alg(
      egg_layers = Layers, proportion = Proportion, coef = Coefficient
    ),
    Coefficient = paste("Algae coefficient: ", format(Coefficient, digits = 4),
      sep = ""
    )
  )
# Figure
egg_dens_alg_plot <- ggplot(
  data = dat, mapping = aes(x = Layers, y = EggDens, group = Proportion)
) +
  geom_line(mapping = aes(colour = Proportion)) +
  labs(
    x = "Number of egg layers on algae",
    y = expression(paste("Algae egg density (", 10^3 %.% "eggs" %.% "m"^-2, ")",
      sep = ""
    )),
    colour = "Proportion of substrate\ncovered in algae"
  ) +
  scale_y_continuous(labels = comma) +
  scale_colour_viridis() +
  facet_wrap(Coefficient ~ ., ncol = 2) +
  expand_limits(x = 0, y = 0) +
  herring_theme +
  theme(legend.position = "top")
# Show the figure
print(egg_dens_alg_plot)
@

The total understory egg density for quadrat $q$ in transect $t$ and spawn $s$ is
\begin{equation}\label{eqUnderDensQTS}
\rho_{q_{txsnry}} = \rho_{i_{qtxsnry}'} + \sum_{v_{qtxsnry}=1}^{V_{qtxsnry}} \rho_{v_{qtxsnry}},
\end{equation}
where $\rho_{i'}$ is substrate egg density from \autoref{eqUnderDensSubQTS},
$\rho_v$ is egg density on algae $v$ from \autoref{eqUnderDensAlgVQTS}, and
$\rho_q$ is in $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$.
Thus, we assume that eggs on substrate and algae are independent, and can be added without bias.

\subsection{TRANSECT OBSERVATIONS AND CALCULATIONS}\label{secUnderT}

At the transect level (\autoref{figFlow}, step \ref{uTrans}), the mean understory egg density in transect $t$ is
\begin{equation}\label{eqUnderDensTS}
\mean{\rho_{t_{xsnry}}} = \frac{1}{Q_{txsnry}} \sum_{q_{txsnry}=1}^{Q_{txsnry}} \rho_{q_{txsnry}},
\end{equation}
where $Q$ is the number of quadrats in transect $t$,
$\rho_q$ is total understory egg density in quadrat $q$ from \autoref{eqUnderDensQTS}, and
$\mean{\rho_t}$ is in $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$.
Note that we update spawn width to correct for errors regarding
the assumed accuracy of transect lines used to measure spawn width for
understory surveys between \Sexpr{min(under_width_facs$Year)} and \Sexpr{max(under_width_facs$Year)} (\autoref{secWidthUnder}).

\subsection{SPAWN OBSERVATIONS AND CALCULATIONS}\label{secUnderS}

At the spawn level (\autoref{figFlow}, step \ref{uSpawn}), the mean width of spawn $s$ is
\begin{equation}\label{eqUnderWidthMuS}
\mean{W_{s_{nry}}} = \frac{1}{T_{xsnry}} \sum_{t_{xsnry}=1}^{T_{xsnry}} W_{t_{xsnry}},
\end{equation}
where $W_t$ is the spawn width at transect $t$,
$T$ is the number of transects in spawn $s$, and
$\mean{W_s}$ is in metres.
The algae bed length is $L_s''$, also in metres.
As with Macrocystis spawn calculations,
if $L_s''$ is inadvertently not recorded,
we set $L_s''$ to the spawn length $L_s$.
Thus, we assume that eggs on substrate and eggs on algae
are represented by the same length measurement.

Next, we calculate the weighted mean egg density in spawn $s$,
where transect egg density is weighted by spawn width at transect $t$, $W_{ts}$.
We calculate a weighted mean because spawn width varies along the spawn length;
a weighted mean ensures that transects contribute proportionally to their area.
The mean egg density in spawn $s$ is
\begin{equation}\label{eqUnderDensMuS}
\mean{\rho_{s_{nry}}} = \frac{\sum_{t_{xsnry}=1}^{T_{xsnry}} \mean{\rho_{t_{xsnry}}} W_{t_{xsnry}}}
{\sum_{t_{xsnry}=1}^{T_{xsnry}} W_{t_{xsnry}}},
\end{equation}
where $\mean{\rho_t}$ is the mean understory egg density in transect $t$ from \autoref{eqUnderDensTS},
$W_t$ is the spawn width for transect $t$ in metres, and
$\mean{\rho_s}$ is in $10^3 \cdot \text{eggs} \cdot \text{m}^{-2}$.

The understory spawn index in spawn $s$ is
\begin{equation}\label{eqUnderIndS}
B_{s_{nry}}' = \frac{\mean{\rho_{s_{nry}}} L_{s_{nry}}'' \mean{W_{s_{nry}}} 10^3} {\theta},
\end{equation}
where $\mean{\rho_s}$ is the mean understory egg density from \autoref{eqUnderDensMuS},
$L_s''$ is the length of the algae bed,
$\mean{W_s}$ is the mean spawn width from \autoref{eqUnderWidthMuS},
$\theta$ is the egg conversion factor from \autoref{eqECF}, and
$B_s'$ is in tonnes (\autoref{figFlow}, step \ref{uInd}).

\section{TOTAL SPAWN CALCULATIONS}\label{secTotal}

This section describes step \ref{tIndex} (\autoref{figFlow}).
The total spawn index in spawn $s$ (\autoref{tabNotationIndices}) is
\begin{equation}\label{eqTotIndSLRY}
B_{s_{nry}}' = \sum_{x_{snry}=1}^{X_{snry}} B_{x_{snry}}',
\end{equation}
where $B_x'$ is the spawn index for
surface, Macrocystis, and understory spawn surveys from
\autoref{eqSurfIndS}, \autoref{eqMacroIndS}, and \autoref{eqUnderIndS}, respectively, and
$B_s'$ is in tonnes (\autoref{figFlow}, step \ref{tIndex}).

\begin{table}
\centering
\caption[Notation for \fishName{} total spawn index calculations]
{Notation for \fishName{} total spawn index calculations.
Note that in this table $q$ represents the spawn index scaling parameter,
not quadrat number as in other sections of this report.
Legend: tonnes (t).}
\begin{tabulary}{\linewidth}{lLLL}
\toprule
\textbf{Name} & \textbf{Description} & \textbf{Value or unit} & \textbf{References} \\
\midrule
$B'$ & Spawn index (i.e., biomass) & t & \\
$q$ & Spawn index scaling parameter & $0.0 < q \leq 1.0$ & DFO \citeyearpar{DFO2021} \\
$B$ & Scaled abundance (i.e., biomass) & t & \\
\bottomrule
\end{tabulary}
\label{tabNotationTotal}
\end{table}

Finally, we aggregate the total spawn index by SAR $r$ and year $y$
\begin{equation}\label{eqTotIndRY}
B_{ry}' = \sum_{n_{ry}=1}^{N_{ry}} \sum_{s_{nry}=1}^{S_{nry}} B_{s_{nry}}',
\end{equation}
where $B_s'$ is the total spawn index from \autoref{eqTotIndSLRY},
and $B_{ry}'$ is a relative index of combined sex spawning biomass for SAR $r$ and year $y$ in tonnes.

\subsection{SCALED ABUNDANCE}\label{secScaled}

We use $B_{ry}'$ as an indicator of relative population abundance (i.e., biomass)
in \fishName{} stock assessment models \citeyearpar[DFO][]{DFO2021}.
We scale $B_{ry}'$ to abundance
\begin{equation}\label{eqAbundRY}
B_{ry} = \frac{B_{ry}'} {q_{ry}},
\end{equation}
where $B_{ry}'$ is the total spawn index in tonnes from \autoref{eqTotIndRY},
$q_{ry}$ is the spawn index scaling parameter \citeyearpar[DFO][]{DFO2016}, and
$B_{ry}$ is scaled abundance (i.e., biomass) for SAR $r$ and year $y$ in tonnes.
To be consistent with stock assessments,
in this section $q$ represents the spawn index scaling parameter,
not quadrat number as in other sections of this report.
In \fishName{} stock assessment models,
$q$ describes the proportion of spawn observed in spawn surveys,
accounting for egg loss (e.g., due to predation) and
unobserved spawns \citeyearpar[DFO][]{DFO2016}.
Although $q$ is uncertain
and a number of assumptions are made within the assessment model,
there are differences between the proportion of spawn observed in the two spawn survey periods \citeyearpar[DFO][]{DFO2021}.
Therefore, for each SAR we estimate one spawn index scaling parameter for
the surface survey period $q_1$
(\Sexpr{pars$years$assess} to \Sexpr{pars$years$dive-1}), and
a second one for the dive survey period $q_2$
(\Sexpr{pars$years$dive} to present).

\section{SPAWN-ON-KELP CALCULATIONS}\label{secSOK}

Spawn-on-kelp (SOK) fisheries collect \fishName{} roe that adheres to algae such as Macrocystis after spawning.
Other similar fisheries include spawn-on-bough,
in which operators collect roe that adhere to submerged tree boughs;
we refer to these fisheries collectively as SOK in this document.
There are two types of SOK fisheries in BC:
`open-pond' in which operators provide algae to spawning \fishName{}, and
`closed-pond' in which operators impound spawning \fishName{} in floating nets that contain algae \citep{ShieldsEtal1985}.
Although SOK fisheries do not directly remove spawning \fishName{}, they do remove eggs that could otherwise have contributed to recruitment.
Note that closed-pond operations also cause incidental mortality to spawning \fishName{} \citep{ShieldsEtal1985},
but we do not address this issue here.
Thus, SOK fisheries present an issue in terms of their impact to the population,
and accounting in stock assessment and monitoring \citep{SchweigertEtal2018}.
For example, failing to account for SOK spawn in assessments is analogous to
treating it as missed spawn via the $q$ parameter (\autoref{secScaled});
conversely, accounting for SOK spawn directly in assessments may reduce the uncertainty in $q$.
Although \fishName{} stock assessments do not account for eggs removed by SOK fisheries at this time,
there are a few options to account for the impact of SOK harvest.
The most direct is to estimate the quantity of eggs removed from the population,
and determine the biomass of \fishName{} that produced those eggs.

\cite{ShieldsEtal1985} collected information on the relationship between
the number of egg layers in SOK product, and
the proportion of product weight that consists of eggs and kelp.
They determined that kelp represents an average of 12\% of the total product weight.
Since SOK product is universally brined at the time of harvest,
it is necessary to also consider the uptake of salt by the eggs,
which increases the overall product weight.
However, there is uncertainty in the degree of brining that occurs prior to weighing the product.
Nevertheless, \cite{WhyteEnglar1977} determined that wet product weight increases
by approximately 13\% due to salt uptake during a 24-hour brining period.
By osmosis, brining would also draw some water from the eggs \citep{AldericeEtal1979};
unfortunately we are unable to account for osmosis at this time.
The last factor to consider is the mean fertilized egg weight,
$2.38 \cdot 10^{-6}\,\text{kg}$ \citep{HayMiller1982}.

We estimate the spawn index for \fishName{} that spawned and produced eggs
which were removed from the population by SOK fishery $g$ (\autoref{tabNotationIndices}) as
\begin{equation}\label{eqSOKBioGRY}
B_{g_{ry}}' = \frac{H_{g_{ry}} \left(1 - \nu\right) \frac{1}{1+\upsilon}} {w \theta},
\end{equation}
where $H_g$ is the weight in kilograms of \fishName{} SOK harvest in fishery $g$,
$\nu$ is the proportion of SOK product weight that is kelp,
$\upsilon$ is the SOK product weight increase due to brining as a proportion,
$w$ is the average weight in kilograms of a fertilized egg,
$\theta$ is the egg conversion factor from \autoref{eqECF}, and
$B_g'$ is in tonnes (\autoref{tabNotationSOK}).
Then we aggregate the spawn index by SAR $r$ and year $y$
\begin{equation}\label{eqSOKBioRY}
B_{ry}' = \sum_{g_{ry}=1}^{G_{ry}} B_{g_{ry}}',
\end{equation}
where $B_g'$ is the spawn index for fishery $g$ from \autoref{eqSOKBioGRY}, and
$B_{ry}'$ is in tonnes.
Thus, $B_{ry}'$ is the estimated \fishName{} biomass that produced eggs
which were removed by SOK fisheries in SAR $r$ and year $y$ in tonnes.

\begin{table}
\centering
\caption[Notation for \fishName{} spawn-on-kelp calculations]
{Notation for \fishName{} spawn-on-kelp (SOK) calculations.
Legend: kilograms (kg), tonnes (t).}
\begin{tabulary}{\linewidth}{lLLL}
\toprule
\textbf{Name} & \textbf{Description} & \textbf{Value or unit} & \textbf{References} \\
\midrule
$H$ & Weight of SOK harvest & kg & \\
$\nu$ & Proportion of SOK product that is kelp & \Sexpr{pars$sok$nu} & \cite{ShieldsEtal1985} \\
$\upsilon$ & SOK product weight increase due to brining (proportion) & \Sexpr{pars$sok$upsilon} & \cite{WhyteEnglar1977} \\
$w$ & Average weight of a fertilized egg & \Sexpr{pars$sok$w}$\,\text{kg}$ & \cite{HayMiller1982} \\
$B'$ & SOK spawn index (i.e., biomass) & t & \\
\bottomrule
\end{tabulary}
\label{tabNotationSOK}
\end{table}

\section{SOURCES OF UNCERTAINTY}\label{secUncertain}

Like all biological models, spawn index calculations are affected by
various potential sources of uncertainty including
natural variability,
observation error (e.g., bias, precision),
measurement error, and
model structural complexity \citep{LinkEtal2012}.
Some examples illustrate these sources of uncertainty:
\begin{enumerate}
\item Natural variability could affect \fishName{} fecundity, and the sex ratio of spawning \fishName{} (\autoref{eqECF}).
Fecundity could be influenced by biological processes such as the observed non-stationarity of weight-at-age \citeyearpar[DFO][]{DFO2021}, or
a truncated age distribution caused by selective fishing \citep{BrunelPiet2013}.
\item Measurement error could affect input data (e.g., number of egg layers, spawn length and width), while
model structural complexity could affect estimated prediction model parameters,
or the form of their relationship, or both (e.g., \autoref{eqSurfDensJS}).
In addition, spawn index prediction models are dated,
and the processes could have changed in the intervening years
(e.g., \autoref{eqSurfDensJS}, \autoref{eqMacroEggsPerPlantS}).
\item Uncertainty in fixed parameters that are used as data without error (e.g., \autoref{eqSurfDensJS});
uncertainty in spawn index parameters is currently unknown.
\item Uncertainty in the number of egg layers for spawn intensity categories (\autoref{tab:Intensity}), and algae coefficients (\autoref{tab:AlgaeCoefs}).
Again, uncertainty in these values is currently unknown.
\end{enumerate}
Despite these assumptions and potential sources of uncertainty,
the spawn index has typically been reported without quantifying uncertainty
(but see \citet{SchweigertEtal1993} who derived a variance estimator).
Reporting the spawn index without uncertainty may perpetuate the misconception
that the spawn index is observed data,
whereas it is derived data with assumptions and uncertainties.
An additional issue for stock assessments is that the model formulation could
interpret the spawn index as being more precise than it actually is,
and estimates of stock status and future prognosis could be artificially precise.

There are several potential benefits to addressing spawn index uncertainty.
First, quantifying uncertainty could identify parameters to target with future research.
Potential analyses to quantify spawn index uncertainty include:
\begin{enumerate}
\item Quantify and report variability in estimated prediction model parameters and equations (e.g., \autoref{eqSurfDensJS}),
\item Propagate uncertainty in parameters and prediction models through spawn index calculations,
\item Incorporate the underlying data that informs prediction model equations into spawn index calculations,
\item Bootstrap observed input data \citep[see][]{Schweigert1993b}, and
\item Conduct sensitivity analyses.
\end{enumerate}
Second, acknowledging uncertainty can reduce another source of uncertainty:
inadequate communication among scientists, managers, and stakeholders,
which can lead to misapplication of scientific advice \citep{LinkEtal2012}.
Finally, acknowledging uncertainty will increase transparency, and
enable users to assess potential impacts to \fishName{} stock assessments
in a management strategy evaluation (MSE) approach \citeyearpar[e.g., DFO][]{DFO2019}.
Addressing data and model uncertainty is a required component of MSE approaches \citep{PuntEtal2016}.

Quantifying uncertainty may also identify options to increase survey program efficiency by
targeting data that have the greatest impact on spawn index accuracy.
In addition, there is a trade-off between precision of estimated quantities versus survey effort or cost.
Ideally, reducing survey effort does not result in biased target variable estimates.
Therefore, understanding this trade-off is important if, for example,
budget reductions cause reduced survey effort.
Potential strategies to improve spawn survey efficiency include:
\begin{enumerate}
\item Conduct underwater surveys for major spawns in core areas, and surface surveys for other spawns,
\item Review transect and quadrat spacing \citep[\autoref{secStat}; see][]{Schweigert1993b}, and
\item Conduct periodic versus annual surveys.
\end{enumerate}
Even with a stable budget,
there is a trade-off between high survey effort in some areas,
versus low survey effort or no information in other areas.

\section{FUTURE RESEARCH}\label{secFuture}

\afterpage{
\FloatBarrier
\begin{landscape}
\begin{longtable}{P{1.5cm}P{5cm}P{5cm}P{3cm}P{3cm}}
\caption[Details for parameters and prediction models used in \fishName{} spawn index calculations]
{Details for studies to quantify parameters and prediction models used in \fishName{} spawn index calculations.
Study details include where, when, and how many samples, when available.
The major stock assessment regions are \Sexpr{paste_nicely(major_regions)} (\autoref{figBC}).
Legend: equation (Eq), sample size ($n$), standard error (SE), standard deviation (SD), spawn-on-kelp (SOK), and not available (NA).} \\
\toprule
\textbf{Parameters} & \textbf{Description} & \textbf{Study details} & \textbf{Uncertainty} & \textbf{References} \\
\midrule
\endfirsthead
\toprule
\multicolumn{5}{c}{\emph{\tablename~\thetable~continued}} \\
\textbf{Parameters} & \textbf{Description} & \textbf{Study details} & \textbf{Uncertainty} & \textbf{References} \\
\midrule
\endhead
\bottomrule
\endfoot
\bottomrule
\endlastfoot
$f_t$, $f_q$ & Parameters for statistical framework (Eq \ref{eqStatSigmaS}). & SoG in 1981 and 1983; WCVI in 1982. & Objective is mean egg density $\text{SE}\leq 25$\%. & \cite{SchweigertEtal1985, SchweigertEtal1990} \\
Intensity & Spawn intensity categories and number of egg layers (\autoref{tab:Intensity}). & NA & NA & \cite{HayKronlund1987, SchweigertStocker1988} \\
$\omega$ & Female fecundity (Eq \ref{eqECF}); values in $\text{eggs} \cdot \text{kg}^{-1}$. & PRD, WCVI, and SoG in 1974 ($n=$ 3,293 fish) and 1980 ($n=$ 1,642); California in 1975 ($n=37$). & 186,800 $\leq \omega \leq$ 224,500; 16,900 $\leq \text{SD} \leq$ 53,500. & \cite{Hay1985, HayBrett1988} \\
$\female$ & Proportion female (Eq \ref{eqECF}). & NA & NA & NA \\
$\alpha$, $\beta$ & Parameters for surface survey egg density model (Eq \ref{eqSurfDensJS}). & Coastwide from 1976 to 1987 ($n=$ 5,111 samples). & NA & \cite{SchweigertEtal1997} \\
$\xi$, $\gamma$, $\delta$, $\epsilon$ & Parameters for number of eggs per Macrocystis plant model (Eq \ref{eqMacroEggsPerPlantS}). & HG in 1981 and 1987 ($n=112$ plants); PRD in 1986 ($n=15$); CC in 1986 ($n=5$); WCVI in 1985 and 1986 ($n=35$). & Model accounts for 78\% of variation in eggs per plant. & \cite{HaegeleSchweigert1990} \\
$\varphi$ & Parameter for substrate egg density model (Eq \ref{eqUnderDensSubQTS}). & SoG in 1976, 1977, and 1978; PRD, CC, and WCVI in 1977. & NA & \cite{HaegeleHumphreys1976, HaegeleHumphreys1978a, HaegeleHumphreys1978b, HaegeleEtal1979} \\
$\vartheta$, $\varrho$, $\varsigma$, $C_v$ & Parameters for algae egg density model (Eq \ref{eqUnderDensAlgVQTS}, \autoref{tab:AlgaeCoefs}). & Coastwide from 1976 to 1987 ($n=$ 5,111 samples). & Model accounts for 40\% of variation in egg density. & \cite{Schweigert2005} \\
$\nu$ & Proportion of SOK product that is kelp (Eq \ref{eqSOKBioGRY}). & HG in 1982 and 1983; PRD in 1982. & $\text{SD}=4.2$. & \cite{ShieldsEtal1985} \\
$\upsilon$ & SOK product weight increase due to brining (proportion; Eq \ref{eqSOKBioGRY}). & SoG ca. 1977. & NA & \cite{WhyteEnglar1977} \\
$w$ & Average weight of a fertilized egg (Eq \ref{eqSOKBioGRY}). & SoG in 1980 ($n=7$ samples). & $\text{SE}=3.4 \times 10^{-7}$. & \cite{HayMiller1982}
\label{tabUncertainty}
\end{longtable}
\end{landscape}
\FloatBarrier
}

Many of the studies to quantify parameters and prediction models used in spawn index calculations are dated (\autoref{tabUncertainty});
these analyses could be reviewed with new information, and updated if required.
In addition, some of these studies had limited number of samples,
limited spatial or temporal range, or both.
In addition to work mentioned here and in \autoref{secUncertain}, potential research includes:
\begin{enumerate}
\item Check the assumed statistical framework for spawn index calculations,
\item Check accuracy and temporal stability of fecundity and sex ratios (\autoref{eqECF}),
\item Compare two methods to calculate the mean number of stalks per plant (\autoref{eqMacroStalksPerPlantS}): ratio of means (i.e., current method) versus mean of ratios,
\item Review the assumptions that eggs on substrate and algae are:
\begin{enumerate}
\item Independent (\autoref{eqUnderDensQTS}), and
\item Represented by the same length measurement (\autoref{secUnderS}),
\end{enumerate}
\item Review surface spawn width adjustments (\autoref{secWidthSurface}):
\begin{enumerate}
\item Mean versus median width,
\item Annual versus periodic updates, and
\item Occurrence of relationship between spawn width and spawning biomass,
\end{enumerate}
\item Periodically review the accuracy of egg density models using egg layer and vegetation cover estimates collected underwater, compared to egg counts in a subset of sampled quadrats,
\item Quantify incidental mortality in SOK operations, and
\item Account for osmosis in SOK calculations (\autoref{eqSOKBioGRY}).
\end{enumerate}

\section{CAVEATS}

There are a few caveats to consider when interpreting the \fishName{} spawn index, and using spawn index data in analyses.
These caveats include:
\begin{enumerate}
\item The spawn index is a relative index of spawning biomass,
\item The spawn survey is a presence only survey;
thus the spawn index is a minimum spawning biomass,
\item There are two different spawn survey periods with substantial differences in survey effort and method (\autoref{secSurfProt}):
\begin{enumerate}
\item Surface period from \Sexpr{pars$years$assess} to \Sexpr{pars$years$dive-1}, and
\item Dive period from \Sexpr{pars$years$dive} to present,
\end{enumerate}
\item Surface spawn surveys use two different methods to estimate the number of egg layers (\autoref{secIntensity}):
\begin{enumerate}
\item Spawn intensity categories:
\begin{enumerate}
\item Five categories from \Sexpr{pars$years$assess} to \Sexpr{pars$years$nine_cats-1}, and
\item Nine categories from \Sexpr{pars$years$nine_cats} to \Sexpr{pars$years$layers-1}, and
\end{enumerate}
\item Direct estimates from \Sexpr{pars$years$layers} to present,
\end{enumerate}
\item The spawn index is derived from surface and dive observations of egg deposition,
and includes uncertainty and assumptions (\autoref{secUncertain}), and
\item Spawn index calculations rely on dated parameters and models (\autoref{secFuture}).
\end{enumerate}

\section{R PACKAGE}\label{secPack}

We created an \textbf{R} \citeyearpar[RCT][]{R-4.0.5-32} package
to implement the calculations described in this document.
The SpawnIndex \textbf{R} package is publicly accessible on the \gitRepo{}.
The SpawnIndex package contains
an example database of \fishName{} spawn survey observations, as well as
functions to import tables from the database, and
functions to calculate the spawn index.
The SpawnIndex package is documented, and
has examples to promote accessibility and transparency.
There is also a vignette with an example workflow.

<<>>=
# Lookup table for parameter names
lookup_pars <- read_csv(
  "Name in TechReport, Symbol in TechReport, Name in R, Description, Context
  theta, \\theta, `theta`, Egg conversion factor, `eggs_to_sb()`"
)
save(lookup_pars, file = file.path("data", "lookup_pars.RData"))
# Cross-walk table for functions
lookup_funs <- read_csv(
  "a, b
  one, two"
)
save(lookup_funs, file = file.path("data", "lookup_funs.RData"))
@

# Cross-walk table for functions
lookup_funs <- read_csv(
  "a, b
  one, two"
)
save(lookup_funs, file = file.path("data", "lookup_funs.RData"))


\section{ACKNOWLEDGEMENTS}

The authors thank Ashleen Benson for translating the calculations
in the \textbf{Microsoft Access} database to an \textbf{R} script,
which they referenced when developing the SpawnIndex package.
They thank Paul Starr and Rob Kronlund for their thorough reviews
that improved this document.
They also thank Andy Edwards for help with mathematical notation.
Finally, they thank Chris Grandin for help creating the \textbf{R} package.

%%%%% References %%%%%

% Style file
\bibliographystyle{\locRes/CJFAS}

% References
\bibliography{../inst/REFERENCES}

%%%%% Appendices %%%%%

% Begin the appendices
\begin{appendices}

% Redefine figures, tables, and equations
\renewcommand\thefigure{\thesection.\arabic{figure}}
\renewcommand\thetable{\thesection.\arabic{table}}
\renewcommand\theequation{\thesection.\arabic{equation}}

\section{SPAWN WIDTH ADJUSTMENTS}\label{secWidthAdjust}

% Reset figure, table, and equation counters
\setcounter{figure}{0}
\setcounter{table}{0}
\setcounter{equation}{0}

Spawn width is a critical component in spawn index calculations.
There are two cases where we adjust spawn width estimates to improve spawn index accuracy:
surface surveys in all years from \Sexpr{pars$years$assess} to present, and
understory dive surveys from \Sexpr{min(under_width_facs$Year)} to \Sexpr{max(under_width_facs$Year)}.

\subsection{SURFACE SPAWN WIDTH}\label{secWidthSurface}

Surface surveys were the only survey type prior to \Sexpr{pars$years$dive},
while the majority of spawns since \Sexpr{pars$years$dive}
have been surveyed using SCUBA gear.
Recall that we describe the spawn index as having two periods
based on the predominant survey type:
surface survey period from \Sexpr{pars$years$assess} to \Sexpr{pars$years$dive-1}, and
dive survey period from \Sexpr{pars$years$dive} to present.

One issue with comparing these two partly overlapping protocols is that
surface surveyors tend to underestimate spawn width \citep{HayKronlund1987}.
To improve the consistency of spawn index estimates throughout the time period
from \Sexpr{pars$years$assess} to present,
we adjust surface spawn width estimates using underwater estimates from dive surveys
when dive data are available \citep{SchweigertEtal1993}.
Our preferred width is the median width from all dive surveys within a `pool.'
A pool is a group of Locations within a Section that are
often adjacent,
contain similar algae and substrate, and
can be treated as a group with likely similar widths.
We summarise spawn width by the median because widths are skewed \citep{SchweigertEtal1993}.
If there are no dive data that meet these criteria,
we use the median width from all dives within the Section,
or within the SAR if there are no dives within the Section.
In the rare instances where no dive data meet these criteria (e.g., outside SAR boundaries),
we use the observed width $W'$ from the surface survey.
We update the aforementioned median width values periodically, not annually.
Note that we use this process to update widths for spawns in previous years using current observations.

\subsection{UNDERSTORY SPAWN WIDTH}\label{secWidthUnder}

In 2013, Fisheries and Oceans Canada (DFO) staff realized that they were
inadvertently underestimating spawn width for
\fishName{} understory dive surveys \citep{ClearyEtal2017}.
The issue was caused by the assumed accuracy of transect lines used by spawn surveyors to measure spawn width.
Spawn surveyors determine spawn width by placing transects perpendicular to the shore.
Surveyors use weighted lead lines to ensure that lines rest on the substrate;
these lines are marked in $1\,\text{m}$ increments, and are standardized to $20\,\text{m}$ segments (i.e., a `chain').
Segments refer to individual sections of line, which can be linked together to make complete transects.

During the late 1990s it became apparent that the $20\,\text{m}$ segments shrank
by approximately $1\,\text{m}$ during the first season of use, and
continued to shrink over time.
DFO staff noticed that this issue was occurring coast wide, and
began re-measuring lead lines each season.
They also modified the lead line marking protocol
to account for shrinkage by marking $1.15\,\text{m}$ increments;
thus, segments were extended to $23\,\text{m}$.
DFO staff derived this 15\% increase by measuring and re-marking lead lines each year.
Lead lines are made of a mix of polypropylene and nylon;
nylon tightens up under repeated use,
which we think explains the shrinkage.
DFO staff re-measured lead line increments in about 2005, and found that
they still shrank from $1.15\,\text{m}$ to $1.0\,\text{m}$, and
continued to use the modified protocol.

In 2013, spawn surveyors observed that
lead line increments were consistently $1.15\,\text{m}$,
and no longer appeared to be shrinking.
Following this observation, DFO staff re-measured additional lead lines
and found that lead lines were made up of a combination of
$1.0\,\text{m}$ and $1.15\,\text{m}$ increments.
The combination of observed increment lengths is explained by the lifespan of lead lines:
lead lines are replaced every 5 to 10 years,
with some segments being replaced more frequently.
For example, inner segments are replaced more frequently than seaward segments, and
segments in some SARs are replaced more frequently than in other SARs.
We believe that a change in lead line manufacturing prevents new lead lines from shrinking.

The earliest written instructions that describe the modified protocol
of marking $1.15\,\text{m}$ increments is from \Sexpr{min(under_width_facs$Year)},
and this protocol was used until 2013.
Note that some remote SARs continued to use old lead lines in \Sexpr{max(under_width_facs$Year)}.
The practice of annually re-measuring lead line increments ceased around 2005;
thus we are unable to determine when lead lines ceased shrinking.
Given the observations summarized above,
we adjust spawn width estimates based on written instructions for the marking protocol in \Sexpr{min(under_width_facs$Year)}.
Accordingly, our best estimate of years impacted by marking lead lines at $1.15\,\text{m}$ increments (when shrinking no longer occurred) is
from \Sexpr{min(under_width_facs$Year)} to \Sexpr{max(under_width_facs$Year)}.
However, not all SARs $r$ and years $y$ are impacted equally by this issue (\autoref{tab:WidthFac}):
some SARs and years had all $1.0\,\text{m}$ increment lengths (no correction factor needed; $\tau_{ry} = 1.000$),
others had all $1.15\,\text{m}$ increment lengths ($\tau_{ry} = 1.150$),
and others had a combination of $1.0\,\text{m}$ and $1.15\,\text{m}$ increment lengths
which we assume to be in equal proportion ($\tau_{ry} = 1.075$).
We correct understory spawn width by multiplying the observed width by the correction factor
\begin{equation}\label{eqWidthCorT}
W_{t_{xsnry}} = W_{t_{xsnry}}' \tau_{ry},
\end{equation}
where $W_t'$ is the observed spawn width for transect $t$,
$\tau_{ry}$ is the spawn width correction factor for SAR $r$ and year $y$ (\autoref{tab:WidthFac}), and
$W_t$ is the corrected understory spawn width in metres (\autoref{tabNotationWidth}).
Instead of updating the database permanently,
we adjust spawn width in the \textbf{R} package to be transparent, and
to prevent mismatches between the original data sheets and databases.
It is now standard practice to re-measure transect segments annually
to ensure that this issue does not reoccur
due to another change in lead line manufacturing.

<<WidthFac>>=
# Caption
tab_cap <- paste("Spawn width correction factors $\\tau_{ry}$ for \\fishName{}
                 understory spawn surveys by stock assessment region (SAR, $r$)
                 and year $y$. Legend: ",
                 paste_nicely(c(major_regions, minor_regions)), ".",
                 sep = ""
)
# Short caption
tab_s_cap <- "Spawn width correction factors for \\fishName{} understory spawn
              surveys"
# Format the table
k_width_fac <- under_width_facs %>%
  mutate_if(is.double, ~ format(., nsmall = 3)) %>%
  mutate(Year = as.integer(Year)) %>%
  arrange(Year) %>%
  kable(
    caption = tab_cap, caption.short = tab_s_cap, booktabs = TRUE, linesep = "",
    escape = FALSE, digits = c(0, 3, 3, 3, 3, 3, 3, 3)
  ) %>%
  row_spec(0, bold = TRUE) %>%
  add_header_above(header = c("", "SAR" = 7), bold = TRUE)
# Print the table
k_width_fac
@

\begin{table}
\centering
\caption[Notation for \fishName{} understory spawn width adjustments]
{Notation for \fishName{} understory spawn width adjustments.
Legend: metres (m).}
\begin{tabulary}{\linewidth}{LLL}
\toprule
\textbf{Name} & \textbf{Description} & \textbf{Value or unit} \\
\midrule
$W'$ & Observed spawn width & m \\
$\tau$ & Spawn width correction factor & See \autoref{tab:WidthFac} \\
$W$ & Corrected spawn width & m \\
\bottomrule
\end{tabulary}
\label{tabNotationWidth}
\end{table}

\section{SURFACE SPAWN UPDATES}\label{secUpdate}

% Reset figure, table, and equation counters
\setcounter{figure}{0}
\setcounter{table}{0}
\setcounter{equation}{0}

One record in the surface spawn database since \Sexpr{pars$years$assess}
requires an update to fill-in missing egg layer information.
As with understory spawn width updates,
we make this update in the \textbf{R} package:
\begin{enumerate}
\item Update `intensity' from 0 to 1 for the records (there is 1 record) in the year 1962, Statistical Area 14, Section 142, Location code 820, and with $\text{intensity} = 0$.
We update intensity from 0 to 1 because spawn was surveyed but not reported.
\end{enumerate}
Spawn survey records prior to \Sexpr{pars$years$assess}
have additional missing or inaccurate egg layer information, and
are unreliable for indexing purposes.
Therefore, we exclude spawn data prior to \Sexpr{pars$years$assess}
from stock assessments.

While reviewing spawn index calculations and translating them from
a \textbf{Microsoft Access} database to \textbf{R},
we found several cases where index data were being over-written with no documented reason.
These updates have been omitted, and affected the following records:
\begin{enumerate}
\item Update $E_j$ (i.e., number of egg layers; \autoref{tabNotationSurf}) to 2.1496 for the records (there are 15 records) in the year 1979, Statistical Area 2, and with intensity 4,
\item Update $E_j$ to 0.5529 for the records (4) in the year 1981, Statistical Area 24, and with $E_j = 0.0$,
\item Update $E_j$ to 1.3360 for the records (7) in the year 1982, Statistical Area 23, and with intensity 3,
\item Update $E_j$ to 2.3300 for the records (41) in the year 1984, Statistical Area 24, and with intensity 0, and
\item Update $E_j$ to 2.9800 for the records (14) in the year 1982, Statistical Area 27, and with $E_j = 0.0$.
\end{enumerate}
In the first three cases,
$E_j$ was updated using intensity categories (\autoref{tab:Intensity});
in the last two cases,
$E_j$ was updated using historical averages.
These changes have negligible effects on spawn index values.

% End appendices
\end{appendices}

%%%%% Fin %%%%%

% The end
\end{document}
