utils::globalVariables(c(
  "AlgLyrs", "AlgProp", "AlgType", "Area", "BED", "Bed", "BrownAlgae",
  "Brown_Algae_Percent", "Coef", "Depth", "DepthM", "Eastings", "EggDens",
  "EggDensAlg", "EggDensSub", "EggLyrs", "EggsPerPlant", "End", "Grass",
  "Grass_Percent", "Group", "Height", "Intensity", "Kelp", "Kelp_Percent",
  "Latitude", "Lay_Brown_Algae", "Lay_Grass", "Lay_Kelp", "Lay_Leafy_Red",
  "Lay_Other", "Lay_Rock", "Lay_Rockweed", "Lay_Stringy_Red", "Layers",
  "Layers_Bottom", "Layers_Vegetation", "LeafyRed", "Leafy_Red_Percent",
  "Length", "LengthAlgae", "LengthMacro", "Length_Macrocystis",
  "Length_Vegetation", "Loc_Code", "Location", "LocationCode", "LocationName",
  "Location_Latitude", "Location_Longitude", "Longitude", "MacroSI", "Major",
  "Mature", "Method", "Northings", "Other", "Other_Percent", "Percent_Bottom",
  "Percent_Vegetation", "Plants", "Pool", "QuadratSize", "Quadrat_Size",
  "REGION", "Region", "RegionName", "Rock", "Rock_Percent", "Rockweed",
  "Rockweed_Percent", "SAR", "SECTION", "Section", "SpawnNumber",
  "Spawn_Number", "Stalks", "StalksPerPlant", "Start", "StatArea", "Station",
  "StringyRed", "Stringy_Red_Percent", "SubLyrs", "SubProp", "SurfSI", "Swath",
  "Transect", "Type_Vegetation", "UnderSI", "WIDMED", "Width", "WidthBar",
  "WidthFac", "WidthObs", "WidthPool", "WidthReg", "WidthSec", "Width_Recorded",
  "X", "Y", "Year", "algae_coefs", "areas", "intensity", "pars",
  "under_width_facs"
))
